import { resolveLang, type Lang } from './lang';

// UI 文言の多言語辞書。ja / en / ko / zh / de / fr / es / ru を用意する。
// ある言語のキーが無い場合はすべて ja にフォールバックする。
// ニュース記事のタイトル・本文は microCMS の title_*/content_* 側で翻訳するため、ここには含めない。
// メール本文・件名・payload のキーは担当者向けなので日本語のまま（辞書対象外）。
type Localized = {
  ja: string;
  en?: string;
  ko?: string;
  zh?: string;
  de?: string;
  fr?: string;
  es?: string;
  ru?: string;
};

const UI_STRINGS = {
  // トップページの h1（視覚的には隠し、スクリーンリーダー / SEO 向け）
  homeHeading: {
    ja: 'AXelWorks｜AIとともに、多言語で世界とつながる',
    en: 'AXelWorks — connecting with the world in many languages, together with AI',
    ko: 'AXelWorks｜AI와 함께, 다국어로 세계와 연결된다',
    zh: 'AXelWorks｜与 AI 一同，用多种语言连接世界',
    de: 'AXelWorks – gemeinsam mit KI und in vielen Sprachen die Welt verbinden',
    fr: "AXelWorks — se relier au monde en plusieurs langues, aux côtés de l'IA",
    es: 'AXelWorks — conectar con el mundo en muchos idiomas, junto con la IA',
    ru: 'AXelWorks — связываем мир на многих языках вместе с ИИ',
  },

  // ヘッダー / フッター共通のナビゲーション
  navNews: {
    ja: 'ニュース',
    en: 'News',
    ko: '뉴스',
    zh: '新闻',
    de: 'Aktuelles',
    fr: 'Actualités',
    es: 'Noticias',
    ru: 'Новости',
  },
  navBusiness: {
    ja: '事業内容',
    en: 'Business',
    ko: '사업 내용',
    zh: '业务内容',
    de: 'Geschäftsfelder',
    fr: 'Activités',
    es: 'Servicios',
    ru: 'Услуги',
  },
  navAbout: {
    ja: '私たちについて',
    en: 'Who we are',
    ko: '회사 소개',
    zh: '关于我们',
    de: 'Über uns',
    fr: 'Qui nous sommes',
    es: 'Quiénes somos',
    ru: 'Кто мы',
  },
  navContact: {
    ja: 'お問い合わせ',
    en: 'Contact',
    ko: '문의하기',
    zh: '联系我们',
    de: 'Kontakt',
    fr: 'Contact',
    es: 'Contacto',
    ru: 'Контакты',
  },

  // アクセシビリティ用のラベル
  skipToContent: {
    ja: 'メインコンテンツへスキップ',
    en: 'Skip to main content',
    ko: '본문으로 건너뛰기',
    zh: '跳到主要内容',
    de: 'Zum Hauptinhalt springen',
    fr: 'Aller au contenu principal',
    es: 'Saltar al contenido principal',
    ru: 'Перейти к основному содержанию',
  },
  navMain: {
    ja: 'メインメニュー',
    en: 'Main menu',
    ko: '메인 메뉴',
    zh: '主菜单',
    de: 'Hauptmenü',
    fr: 'Menu principal',
    es: 'Menú principal',
    ru: 'Главное меню',
  },
  navFooter: {
    ja: 'フッターメニュー',
    en: 'Footer menu',
    ko: '푸터 메뉴',
    zh: '页脚菜单',
    de: 'Fußzeilenmenü',
    fr: 'Menu de pied de page',
    es: 'Menú de pie de página',
    ru: 'Меню в подвале',
  },
  menuOpen: {
    ja: 'メニューを開く',
    en: 'Open menu',
    ko: '메뉴 열기',
    zh: '打开菜单',
    de: 'Menü öffnen',
    fr: 'Ouvrir le menu',
    es: 'Abrir el menú',
    ru: 'Открыть меню',
  },
  menuClose: {
    ja: 'メニューを閉じる',
    en: 'Close menu',
    ko: '메뉴 닫기',
    zh: '关闭菜单',
    de: 'Menü schließen',
    fr: 'Fermer le menu',
    es: 'Cerrar el menú',
    ru: 'Закрыть меню',
  },
  paginationLabel: {
    ja: 'ページ送り',
    en: 'Pagination',
    ko: '페이지 매김',
    zh: '分页',
    de: 'Seitennummerierung',
    fr: 'Pagination',
    es: 'Paginación',
    ru: 'Постраничная навигация',
  },
  paginationPage: {
    ja: '{n}ページ目',
    en: 'Page {n}',
    ko: '{n}페이지',
    zh: '第 {n} 页',
    de: 'Seite {n}',
    fr: 'Page {n}',
    es: 'Página {n}',
    ru: 'Страница {n}',
  },
  opensInNewTab: {
    ja: '（新しいタブで開く）',
    en: '(opens in a new tab)',
    ko: '(새 탭에서 열림)',
    zh: '（在新标签页中打开）',
    de: '(wird in einem neuen Tab geöffnet)',
    fr: '(ouvre dans un nouvel onglet)',
    es: '(se abre en una pestaña nueva)',
    ru: '(откроется в новой вкладке)',
  },

  // ヘッダーナビ（/hire-me。日本語のみ）
  navHireMe: { ja: '私を採用情報' },

  // フッター（法的ページのリンク。日本語のみ）
  navTerms: { ja: '利用規約' },
  navPrivacy: { ja: '個人情報保護方針' },
  // {year} は Footer 側で現在の年（new Date().getFullYear()）に置換する
  footerCopyright: {
    ja: '© {year} AXelWorks',
    en: '© {year} AXelWorks',
    ko: '© {year} AXelWorks',
    zh: '© {year} AXelWorks',
    de: '© {year} AXelWorks',
    fr: '© {year} AXelWorks',
    es: '© {year} AXelWorks',
    ru: '© {year} AXelWorks',
  },

  // News セクション
  newsHeading: { ja: 'News' },
  // ニュース一覧ページ（/news, /news/p/N）の h1
  newsListHeading: {
    ja: 'ニュース一覧',
    en: 'News',
    ko: '뉴스 목록',
    zh: '新闻列表',
    de: 'Aktuelles',
    fr: 'Actualités',
    es: 'Noticias',
    ru: 'Новости',
  },
  seeMore: {
    ja: 'もっとみる',
    en: 'See more',
    ko: '더 보기',
    zh: '查看更多',
    de: 'Mehr erfahren',
    fr: 'Voir plus',
    es: 'Ver más',
    ru: 'Подробнее',
  },
  newsListLink: {
    ja: 'ニュース一覧へ',
    en: 'View all news',
    ko: '뉴스 목록 보기',
    zh: '查看全部新闻',
    de: 'Alle News ansehen',
    fr: 'Toutes les actualités',
    es: 'Ver todas las noticias',
    ru: 'Все новости',
  },

  // 記事詳細ページの目次
  tocHeading: {
    ja: '目次',
    en: 'Contents',
    ko: '목차',
    zh: '目录',
    de: 'Inhalt',
    fr: 'Sommaire',
    es: 'Índice',
    ru: 'Содержание',
  },

  // 下層ページのヒーローバナー小見出し（news はバナー廃止済み）
  businessPageHeading: {
    ja: '事業内容',
    en: 'Business',
    ko: '사업 내용',
    zh: '业务内容',
    de: 'Geschäftsfelder',
    fr: 'Activités',
    es: 'Servicios',
    ru: 'Услуги',
  },

  // ページ読み上げコントロール
  readAloudPlay: {
    ja: 'このページを読み上げる',
    en: 'Read this page aloud',
    ko: '이 페이지 읽어주기',
    zh: '朗读此页面',
    de: 'Diese Seite vorlesen',
    fr: 'Lire cette page à voix haute',
    es: 'Leer esta página en voz alta',
    ru: 'Озвучить эту страницу',
  },
  readAloudPause: {
    ja: '読み上げを一時停止',
    en: 'Pause reading',
    ko: '읽기 일시정지',
    zh: '暂停朗读',
    de: 'Vorlesen pausieren',
    fr: 'Suspendre la lecture',
    es: 'Pausar la lectura',
    ru: 'Приостановить озвучивание',
  },
  readAloudStop: {
    ja: '読み上げを停止',
    en: 'Stop reading',
    ko: '읽기 정지',
    zh: '停止朗读',
    de: 'Vorlesen stoppen',
    fr: 'Arrêter la lecture',
    es: 'Detener la lectura',
    ru: 'Остановить озвучивание',
  },
  readAloudSpeed: {
    ja: '速度',
    en: 'Speed',
    ko: '속도',
    zh: '速度',
    de: 'Tempo',
    fr: 'Vitesse',
    es: 'Velocidad',
    ru: 'Скорость',
  },

  // Business セクション
  businessHeading: { ja: 'Business' },
  businessSubtitle: {
    ja: '事業内容',
    en: 'Our business',
    ko: '사업 소개',
    zh: '业务介绍',
    de: 'Unser Angebot',
    fr: 'Notre activité',
    es: 'Nuestra actividad',
    ru: 'Наша деятельность',
  },
  businessBody1: {
    ja: '当社は、次世代テクノロジーの研究開発・製造・販売を行う革新的な企業です。',
    en: 'We are an innovative company engaged in the research, development, manufacturing, and sales of next-generation technology.',
    ko: '당사는 차세대 기술의 연구개발·제조·판매를 하는 혁신적인 기업입니다.',
    zh: '我们是一家从事新一代技术研发、制造与销售的创新型企业。',
    de: 'Wir sind ein innovatives Unternehmen für Forschung, Entwicklung, Fertigung und Vertrieb von Technologien der nächsten Generation.',
    fr: 'Nous sommes une entreprise innovante spécialisée dans la recherche, le développement, la fabrication et la commercialisation de technologies de nouvelle génération.',
    es: 'Somos una empresa innovadora dedicada a la investigación, el desarrollo, la fabricación y la venta de tecnología de nueva generación.',
    ru: 'Мы — инновационная компания, занимающаяся исследованиями, разработкой, производством и продажей технологий нового поколения.',
  },
  businessBody2: {
    ja: 'AI、ロボット工学、自律システムなど、幅広い分野でのソリューション提供を通じて、社会の進化と未来の創造に貢献します。',
    en: 'Through solutions across a wide range of fields — AI, robotics, autonomous systems and more — we contribute to the advancement of society and the creation of the future.',
    ko: 'AI, 로보틱스, 자율 시스템 등 폭넓은 분야에서 솔루션을 제공하며, 사회의 발전과 미래 창조에 기여합니다.',
    zh: '我们通过在人工智能、机器人工程、自主系统等广泛领域提供解决方案，助力社会进步与未来创造。',
    de: 'Mit Lösungen in vielfältigen Bereichen – KI, Robotik, autonome Systeme und mehr – tragen wir zum Fortschritt der Gesellschaft und zur Gestaltung der Zukunft bei.',
    fr: "Grâce à des solutions dans de nombreux domaines — IA, robotique, systèmes autonomes et bien d'autres —, nous contribuons au progrès de la société et à la construction de l'avenir.",
    es: 'A través de soluciones en una amplia variedad de campos —IA, robótica, sistemas autónomos y más—, contribuimos al avance de la sociedad y a la creación del futuro.',
    ru: 'Предлагая решения в самых разных областях — искусственный интеллект, робототехника, автономные системы и многое другое, — мы вносим вклад в развитие общества и создание будущего.',
  },

  // About Us セクション
  aboutHeading: { ja: 'About Us' },
  aboutSubtitle: {
    ja: '私たちについて',
    en: 'Who we are',
    ko: '회사 소개',
    zh: '关于我们',
    de: 'Über uns',
    fr: 'Qui nous sommes',
    es: 'Quiénes somos',
    ru: 'Кто мы',
  },
  // トップページの要約。全文は /company ページ
  aboutLead: {
    ja: '社員は一人。でも、仕事は一人でやらない。',
    en: 'One employee. But no one here works alone.',
    ko: '직원은 한 명. 하지만 일은 혼자 하지 않습니다.',
    zh: '员工只有一人，但工作从不独自完成。',
    de: 'Ein Mitarbeiter. Aber hier arbeitet niemand allein.',
    fr: 'Un seul employé. Mais personne ne travaille seul ici.',
    es: 'Un solo empleado. Pero aquí nadie trabaja solo.',
    ru: 'Один сотрудник. Но здесь никто не работает в одиночку.',
  },
  aboutSummary: {
    ja: 'AIと人がお互いの得意で働き、企業の「面倒」を減らすアプリと、人の「学びたい」を後押しするアプリをつくっています。',
    en: 'People and AI each play to their strengths, building apps that cut business busywork and apps that back people who want to learn.',
    ko: 'AI와 사람이 각자의 강점을 살려, 기업의 ‘번거로움’을 줄이는 앱과 사람의 ‘배우고 싶다’를 돕는 앱을 만듭니다.',
    zh: 'AI 与人各展所长，打造为企业减少繁琐事务的应用，以及支持人们求知的应用。',
    de: 'Mensch und KI bringen jeweils ihre Stärken ein und entwickeln Apps, die Unternehmen lästige Arbeit ersparen, und Apps, die Lernwillige unterstützen.',
    fr: "L'humain et l'IA jouent chacun de leurs forces pour créer des applications qui allègent les corvées des entreprises et d'autres qui soutiennent celles et ceux qui veulent apprendre.",
    es: 'Las personas y la IA aportan cada una sus fortalezas para crear aplicaciones que reducen las tareas tediosas de las empresas y otras que apoyan a quienes quieren aprender.',
    ru: 'Человек и ИИ используют свои сильные стороны и создают приложения, которые избавляют бизнес от рутины, и приложения для тех, кто хочет учиться.',
  },

  // トップページの「私を採用情報」誘導セクション（/hire-me へ）。
  // 「私を採用情報」は日本語の言葉遊びのため subtitle / body / link は日本語のみ。
  hireMeHeading: { ja: 'Hire me' },
  hireMeSubtitle: { ja: '私を採用情報' },
  hireMeBody1: {
    ja: '「採用情報」という言葉ですが、このページで採用されようとしているのは私です。受託でも、雇用でも、私と、一緒に働くAIエージェントたちを、あなたの仕事に組み込んでみませんか。',
  },
  hireMeBody2: {
    ja: '39年のIT業界での経験と、AIエージェントとの新しい働き方について、詳しくご紹介しています。',
  },
  hireMeLink: {
    ja: '私を採用情報へ',
  },

  // 事業内容ページ末尾の問い合わせ誘導セクション（トップの商談予約フォームへ遷移）
  businessContactHeading: {
    ja: 'お問い合わせ',
    en: 'Contact',
    ko: '문의하기',
    zh: '联系我们',
    de: 'Kontakt',
    fr: 'Contact',
    es: 'Contacto',
    ru: 'Связаться с нами',
  },
  businessContactBody: {
    ja: 'ご相談・お見積もりなど、お気軽にお問い合わせください。',
    en: 'Questions, estimates, or an idea to talk through — feel free to get in touch.',
    ko: '상담·견적 등 무엇이든 편하게 문의해 주세요.',
    zh: '咨询、报价或任何想法，都欢迎随时与我们联系。',
    de: 'Ob Beratung, Kostenvoranschlag oder erste Idee – kontaktieren Sie uns gern.',
    fr: 'Questions, devis ou simple idée à échanger : n’hésitez pas à nous contacter.',
    es: 'Consultas, presupuestos o cualquier idea que quiera comentar: escríbanos sin compromiso.',
    ru: 'Консультация, смета или просто идея для обсуждения — напишите нам.',
  },
  businessContactLink: {
    ja: 'お問い合わせフォームへ',
    en: 'Go to the contact form',
    ko: '문의 폼으로 이동',
    zh: '前往咨询表单',
    de: 'Zum Kontaktformular',
    fr: 'Accéder au formulaire de contact',
    es: 'Ir al formulario de contacto',
    ru: 'Перейти к форме обращения',
  },

  // ----- Contact セクション（左カラム） -----
  contactEyebrow: { ja: 'CONTACT' },
  contactHeadingLead: {
    ja: 'その「ちょっと困った」、',
    en: 'That "I\'m a little stuck" —',
    ko: '그 “조금 곤란한 일”,',
    zh: '你那点“小小的烦恼”，',
    de: 'Ihr „kleines Problem“ –',
    fr: 'Ce petit « souci » qui vous bloque,',
    es: 'Ese pequeño «problema» que le frena,',
    ru: 'Та самая «небольшая загвоздка»,',
  },
  contactHeadingAccent: {
    ja: '聞かせてください。',
    en: "let's talk it through.",
    ko: '들려주세요.',
    zh: '说给我们听听吧。',
    de: 'erzählen Sie es uns.',
    fr: 'parlons-en ensemble.',
    es: 'cuéntenoslo.',
    ru: 'расскажите нам о ней.',
  },
  contactLead1: {
    ja: 'まだアイデアが固まっていなくても大丈夫です。',
    en: "It's fine if your idea isn't fully formed yet.",
    ko: '아직 아이디어가 명확하지 않아도 괜찮습니다.',
    zh: '即使想法尚未成型也没关系。',
    de: 'Es macht nichts, wenn Ihre Idee noch nicht ausgereift ist.',
    fr: "Peu importe si votre idée n'est pas encore aboutie.",
    es: 'No pasa nada si su idea aún no está del todo definida.',
    ru: 'Ничего страшного, если ваша идея ещё не оформилась.',
  },
  contactLead2: {
    ja: 'できることから、一緒に考えます。',
    en: "We'll figure out the next step together.",
    ko: '할 수 있는 것부터 함께 고민하겠습니다.',
    zh: '我们会从力所能及之处，与你一起思考。',
    de: 'Wir überlegen gemeinsam den nächsten Schritt.',
    fr: 'Nous réfléchirons ensemble à la prochaine étape.',
    es: 'Pensaremos juntos en el siguiente paso.',
    ru: 'Вместе подумаем над следующим шагом.',
  },
  contactService1: {
    ja: 'AIエージェント実装支援（法人向けコンサルティング）',
    en: 'AI agent implementation support (consulting for businesses)',
    ko: 'AI 에이전트 구축 지원(법인 대상 컨설팅)',
    zh: 'AI 智能体落地支持（面向企业的咨询）',
    de: 'Unterstützung bei der Einführung von KI-Agenten (Beratung für Unternehmen)',
    fr: "Accompagnement à la mise en œuvre d'agents IA (conseil aux entreprises)",
    es: 'Apoyo en la implementación de agentes de IA (consultoría para empresas)',
    ru: 'Поддержка внедрения ИИ-агентов (консалтинг для компаний)',
  },
  contactService2: {
    ja: '受託開発・SaaS開発',
    en: 'Contract development & SaaS development',
    ko: '수탁 개발·SaaS 개발',
    zh: '受托开发·SaaS 开发',
    de: 'Auftragsentwicklung & SaaS-Entwicklung',
    fr: 'Développement sur mesure et développement SaaS',
    es: 'Desarrollo por encargo y desarrollo SaaS',
    ru: 'Разработка на заказ и разработка SaaS',
  },
  contactService3: {
    ja: 'AI・IT研修事業「AX Academy」',
    en: 'AI & IT training — "AX Academy"',
    ko: 'AI·IT 교육 사업 ‘AX Academy’',
    zh: 'AI·IT 培训业务“AX Academy”',
    de: 'KI- und IT-Schulungen – „AX Academy“',
    fr: 'Formations IA et IT « AX Academy »',
    es: 'Formación en IA e IT «AX Academy»',
    ru: 'Обучение ИИ и ИТ «AX Academy»',
  },

  // ----- Contact フォーム -----
  formName: {
    ja: 'お名前',
    en: 'Name',
    ko: '이름',
    zh: '姓名',
    de: 'Name',
    fr: 'Nom',
    es: 'Nombre',
    ru: 'Имя',
  },
  formNamePlaceholder: {
    ja: '山田 太郎',
    en: 'Jane Doe',
    ko: '홍길동',
    zh: '张三',
    de: 'Max Mustermann',
    fr: 'Jean Dupont',
    es: 'Juan Pérez',
    ru: 'Иван Иванов',
  },
  formEmail: {
    ja: 'メールアドレス',
    en: 'Email',
    ko: '이메일 주소',
    zh: '电子邮箱',
    de: 'E-Mail-Adresse',
    fr: 'Adresse e-mail',
    es: 'Correo electrónico',
    ru: 'Электронная почта',
  },
  formConsultation: {
    ja: 'ご相談内容',
    en: 'What would you like to discuss?',
    ko: '문의 내용',
    zh: '咨询内容',
    de: 'Worum geht es?',
    fr: 'Votre demande',
    es: '¿Sobre qué desea hablar?',
    ru: 'Ваш запрос',
  },
  formConsultationPlaceholder: {
    ja: '選択してください',
    en: 'Please select',
    ko: '선택해 주세요',
    zh: '请选择',
    de: 'Bitte wählen',
    fr: 'Sélectionnez',
    es: 'Seleccione una opción',
    ru: 'Выберите',
  },
  formMessage: {
    ja: 'メッセージ',
    en: 'Message',
    ko: '메시지',
    zh: '留言',
    de: 'Nachricht',
    fr: 'Message',
    es: 'Mensaje',
    ru: 'Сообщение',
  },
  formMessagePlaceholder: {
    ja: 'まだぼんやりした内容でも、お気軽にどうぞ。',
    en: 'Even a rough idea is fine — feel free to write.',
    ko: '아직 막연한 내용이라도 편하게 남겨 주세요.',
    zh: '即使还只是模糊的想法，也请随意填写。',
    de: 'Auch eine grobe Idee genügt – schreiben Sie einfach.',
    fr: 'Même une idée encore vague suffit — écrivez-nous librement.',
    es: 'Aunque sea una idea aún vaga, escríbanos sin problema.',
    ru: 'Даже если идея пока размытая, пишите смело.',
  },
  formRequired: {
    ja: '必須',
    en: 'Required',
    ko: '필수',
    zh: '必填',
    de: 'Pflichtfeld',
    fr: 'Obligatoire',
    es: 'Obligatorio',
    ru: 'Обязательно',
  },
  formOptional: {
    ja: '任意',
    en: 'Optional',
    ko: '선택',
    zh: '选填',
    de: 'Optional',
    fr: 'Facultatif',
    es: 'Opcional',
    ru: 'Необязательно',
  },
  formCalendarLegend: {
    ja: 'Google Meet相談（顔出し不要）の候補日時を選択してください（最大{max}件）',
    en: 'Choose up to {max} preferred times for a Google Meet call (camera optional)',
    ko: 'Google Meet 상담(얼굴 공개 불필요) 희망 일시를 선택해 주세요(최대 {max}건)',
    zh: '请选择 Google Meet 咨询（无需露脸）的候选日期时间（最多 {max} 个）',
    de: 'Wählen Sie bis zu {max} Wunschtermine für ein Google-Meet-Gespräch (Kamera optional)',
    fr: "Choisissez jusqu'à {max} créneaux pour un échange sur Google Meet (caméra facultative)",
    es: 'Elija hasta {max} horarios para una reunión por Google Meet (cámara opcional)',
    ru: 'Выберите до {max} вариантов даты и времени для встречи в Google Meet (камера по желанию)',
  },
  formCalendarNote: {
    ja: '直近の営業日から自動で3日分表示しています',
    en: 'Showing the next 3 business days automatically',
    ko: '가장 가까운 영업일부터 자동으로 3일치를 표시합니다',
    zh: '自动显示从最近工作日起的 3 天',
    de: 'Es werden automatisch die nächsten 3 Werktage angezeigt',
    fr: "Les 3 prochains jours ouvrés s'affichent automatiquement",
    es: 'Se muestran automáticamente los próximos 3 días hábiles',
    ru: 'Автоматически показаны ближайшие 3 рабочих дня',
  },
  formTimeColumn: {
    ja: '時間帯',
    en: 'Time',
    ko: '시간대',
    zh: '时间段',
    de: 'Uhrzeit',
    fr: 'Horaire',
    es: 'Franja horaria',
    ru: 'Время',
  },
  formSlotClosed: {
    ja: '（受付終了）',
    en: '(closed)',
    ko: '(마감)',
    zh: '（已截止）',
    de: '(geschlossen)',
    fr: '(clôturé)',
    es: '(cerrado)',
    ru: '(приём закрыт)',
  },
  formSlotsCounter: {
    ja: '{n} / {max}件選択中',
    en: '{n} of {max} selected',
    ko: '{n} / {max}건 선택 중',
    zh: '已选择 {n} / {max} 个',
    de: '{n} von {max} ausgewählt',
    fr: '{n} / {max} sélectionné(s)',
    es: '{n} / {max} seleccionados',
    ru: 'Выбрано {n} / {max}',
  },
  formSubmit: {
    ja: '相談内容を送る',
    en: 'Send message',
    ko: '상담 내용 보내기',
    zh: '发送咨询内容',
    de: 'Nachricht senden',
    fr: 'Envoyer le message',
    es: 'Enviar mensaje',
    ru: 'Отправить сообщение',
  },
  formSubmitting: {
    ja: '送信中…',
    en: 'Sending…',
    ko: '전송 중…',
    zh: '发送中…',
    de: 'Wird gesendet…',
    fr: 'Envoi en cours…',
    es: 'Enviando…',
    ru: 'Отправка…',
  },
  formSubmitNote: {
    ja: '入力内容と選択した候補日時を、担当者へメールで送信します。',
    en: 'Your details and selected times will be emailed to our team.',
    ko: '입력하신 내용과 선택한 희망 일시를 담당자에게 이메일로 전송합니다.',
    zh: '您填写的内容和所选候选时间将通过邮件发送给我们的负责人。',
    de: 'Ihre Angaben und die gewählten Termine werden per E-Mail an unser Team gesendet.',
    fr: 'Vos informations et les créneaux choisis seront transmis par e-mail à notre équipe.',
    es: 'Sus datos y los horarios seleccionados se enviarán por correo a nuestro equipo.',
    ru: 'Ваши данные и выбранные варианты времени будут отправлены нашей команде по электронной почте.',
  },
  formSuccessTitle: {
    ja: '送信しました。ありがとうございます。',
    en: 'Sent — thank you!',
    ko: '전송되었습니다. 감사합니다.',
    zh: '已发送，谢谢您！',
    de: 'Gesendet – vielen Dank!',
    fr: 'Envoyé – merci !',
    es: 'Enviado. ¡Gracias!',
    ru: 'Отправлено. Спасибо!',
  },
  formSuccessBody: {
    ja: '担当者が内容を確認のうえ、いただいたメールアドレス宛に日程のご連絡をいたします。通常2〜3営業日以内にご返信します。',
    en: 'Our team will review your message and email you to arrange a time, usually within 2–3 business days.',
    ko: '담당자가 내용을 확인한 후, 남겨 주신 이메일 주소로 일정을 안내해 드립니다. 보통 2~3영업일 이내에 답변드립니다.',
    zh: '我们的负责人确认内容后，会通过您提供的邮箱与您联系确定日程。通常在 2～3 个工作日内回复。',
    de: 'Unser Team prüft Ihre Nachricht und meldet sich per E-Mail zur Terminabstimmung – in der Regel innerhalb von 2–3 Werktagen.',
    fr: "Notre équipe examinera votre message et vous écrira par e-mail pour convenir d'un rendez-vous, généralement sous 2 à 3 jours ouvrés.",
    es: 'Nuestro equipo revisará su mensaje y le escribirá por correo para concertar una cita, normalmente en un plazo de 2 a 3 días hábiles.',
    ru: 'Наша команда рассмотрит ваше сообщение и напишет вам на указанный адрес электронной почты, чтобы согласовать время — обычно в течение 2–3 рабочих дней.',
  },

  // ご相談内容の選択肢
  consultAgent: {
    ja: 'AIエージェント実装相談',
    en: 'AI agent implementation',
    ko: 'AI 에이전트 구축 상담',
    zh: 'AI 智能体落地咨询',
    de: 'Einführung von KI-Agenten',
    fr: "Mise en œuvre d'agents IA",
    es: 'Implementación de agentes de IA',
    ru: 'Внедрение ИИ-агентов',
  },
  consultDev: {
    ja: '受託開発・SaaS開発相談',
    en: 'Contract / SaaS development',
    ko: '수탁 개발·SaaS 개발 상담',
    zh: '受托开发·SaaS 开发咨询',
    de: 'Auftrags- / SaaS-Entwicklung',
    fr: 'Développement sur mesure / SaaS',
    es: 'Desarrollo por encargo / SaaS',
    ru: 'Разработка на заказ / SaaS',
  },
  consultTraining: {
    ja: 'AI・IT研修相談（AX Academy）',
    en: 'AI & IT training (AX Academy)',
    ko: 'AI·IT 교육 상담(AX Academy)',
    zh: 'AI·IT 培训咨询（AX Academy）',
    de: 'KI- & IT-Schulungen (AX Academy)',
    fr: 'Formations IA et IT (AX Academy)',
    es: 'Formación en IA e IT (AX Academy)',
    ru: 'Обучение ИИ и ИТ (AX Academy)',
  },
  consultOther: {
    ja: 'その他',
    en: 'Other',
    ko: '기타',
    zh: '其他',
    de: 'Sonstiges',
    fr: 'Autre',
    es: 'Otro',
    ru: 'Другое',
  },

  // バリデーションエラー
  errNameRequired: {
    ja: 'お名前を入力してください',
    en: 'Please enter your name.',
    ko: '이름을 입력해 주세요',
    zh: '请输入您的姓名',
    de: 'Bitte geben Sie Ihren Namen ein.',
    fr: 'Veuillez saisir votre nom.',
    es: 'Introduzca su nombre.',
    ru: 'Введите ваше имя.',
  },
  errEmailRequired: {
    ja: 'メールアドレスを入力してください',
    en: 'Please enter your email address.',
    ko: '이메일 주소를 입력해 주세요',
    zh: '请输入电子邮箱',
    de: 'Bitte geben Sie Ihre E-Mail-Adresse ein.',
    fr: 'Veuillez saisir votre adresse e-mail.',
    es: 'Introduzca su correo electrónico.',
    ru: 'Введите адрес электронной почты.',
  },
  errEmailInvalid: {
    ja: 'メールアドレスの形式が正しくありません',
    en: 'Please enter a valid email address.',
    ko: '이메일 주소 형식이 올바르지 않습니다',
    zh: '电子邮箱格式不正确',
    de: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    fr: 'Veuillez saisir une adresse e-mail valide.',
    es: 'Introduzca un correo electrónico válido.',
    ru: 'Введите корректный адрес электронной почты.',
  },
  errConsultationRequired: {
    ja: 'ご相談内容を選択してください',
    en: 'Please select a topic.',
    ko: '문의 내용을 선택해 주세요',
    zh: '请选择咨询内容',
    de: 'Bitte wählen Sie ein Thema.',
    fr: 'Veuillez sélectionner un sujet.',
    es: 'Seleccione un tema.',
    ru: 'Выберите тему.',
  },
  errSlotsRequired: {
    ja: '候補日時を1件以上選択してください',
    en: 'Please select at least one time slot.',
    ko: '희망 일시를 1건 이상 선택해 주세요',
    zh: '请至少选择一个候选时间',
    de: 'Bitte wählen Sie mindestens einen Termin.',
    fr: 'Veuillez sélectionner au moins un créneau.',
    es: 'Seleccione al menos un horario.',
    ru: 'Выберите хотя бы один вариант времени.',
  },
  errSubmitFailed: {
    ja: '送信に失敗しました。お手数ですが時間をおいて再度お試しいただくか、直接メールにてご連絡ください。',
    en: 'Something went wrong. Please try again later, or contact us directly by email.',
    ko: '전송에 실패했습니다. 번거로우시겠지만 잠시 후 다시 시도하시거나, 이메일로 직접 연락해 주세요.',
    zh: '发送失败。请稍后重试，或直接通过邮件与我们联系。',
    de: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es später erneut oder kontaktieren Sie uns direkt per E-Mail.',
    fr: "Une erreur s'est produite. Veuillez réessayer plus tard ou nous contacter directement par e-mail.",
    es: 'Se ha producido un error. Vuelva a intentarlo más tarde o contáctenos directamente por correo.',
    ru: 'Произошла ошибка. Повторите попытку позже или свяжитесь с нами напрямую по электронной почте.',
  },
  errNetwork: {
    ja: 'ネットワークエラーにより送信できませんでした。通信環境をご確認のうえ再度お試しください。',
    en: "Couldn't send due to a network error. Please check your connection and try again.",
    ko: '네트워크 오류로 전송하지 못했습니다. 통신 환경을 확인하신 후 다시 시도해 주세요.',
    zh: '因网络错误未能发送。请检查网络连接后重试。',
    de: 'Aufgrund eines Netzwerkfehlers konnte nicht gesendet werden. Bitte prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
    fr: "L'envoi a échoué en raison d'une erreur réseau. Veuillez vérifier votre connexion et réessayer.",
    es: 'No se pudo enviar debido a un error de red. Compruebe su conexión e inténtelo de nuevo.',
    ru: 'Не удалось отправить из-за сетевой ошибки. Проверьте подключение и повторите попытку.',
  },
  errNotConfigured: {
    ja: '送信設定が未完了のため送信できませんでした。お手数ですが時間をおいて再度お試しください。',
    en: "The form isn't fully configured yet. Please try again later.",
    ko: '전송 설정이 완료되지 않아 전송하지 못했습니다. 번거로우시겠지만 잠시 후 다시 시도해 주세요.',
    zh: '由于发送设置尚未完成，未能发送。请稍后重试。',
    de: 'Das Formular ist noch nicht vollständig konfiguriert. Bitte versuchen Sie es später erneut.',
    fr: "Le formulaire n'est pas encore entièrement configuré. Veuillez réessayer plus tard.",
    es: 'El formulario aún no está del todo configurado. Vuelva a intentarlo más tarde.',
    ru: 'Форма ещё не полностью настроена. Повторите попытку позже.',
  },
} satisfies Record<string, Localized>;

export type UiStringKey = keyof typeof UI_STRINGS;

// 指定キーの文言を lang に応じて返す。lang は Cookie / searchParams で解決済みの値を渡す。
// 対象言語のキーが無ければ日本語にフォールバックする。
// {n} / {max} などのプレースホルダを含むキーは呼び出し側で置換する。
export const ui = (key: UiStringKey, lang: Lang | string | undefined): string => {
  const entry: Localized = UI_STRINGS[key];
  const resolved = resolveLang(lang);
  return (resolved !== 'ja' && entry[resolved]) || entry.ja;
};
