import { resolveLang, type Lang } from './lang';

// UI 文言の多言語辞書。ja / en / ko / zh / de / fr / es / ru を用意する。
// ある言語のキーが無い場合はすべて ja にフォールバックする。
// ニュース記事のタイトル・本文は microCMS の title_*/content_* 側で翻訳するため、ここには含めない。
// メール本文・件名・payload のキーは担当者向けなので日本語のまま（辞書対象外）。
type Localized = {
  ja: string;
  en?: string;
  ko?: string;
  zh?: string;
  de?: string;
  fr?: string;
  es?: string;
  ru?: string;
};

const UI_STRINGS = {
  // トップページの h1（視覚的には隠し、スクリーンリーダー / SEO 向け）
  homeHeading: {
    ja: 'AXelWorks｜AIとともに、多言語で世界とつながる',
    en: 'AXelWorks — connecting with the world in many languages, together with AI',
    ko: 'AXelWorks｜AI와 함께, 다국어로 세계와 연결된다',
    zh: 'AXelWorks｜与 AI 一同，用多种语言连接世界',
    de: 'AXelWorks – gemeinsam mit KI und in vielen Sprachen die Welt verbinden',
    fr: "AXelWorks — se relier au monde en plusieurs langues, aux côtés de l'IA",
    es: 'AXelWorks — conectar con el mundo en muchos idiomas, junto con la IA',
    ru: 'AXelWorks — связываем мир на многих языках вместе с ИИ',
  },

  // ヘッダー / フッター共通のナビゲーション
  navNews: {
    ja: '記事',
    en: 'Articles',
    ko: '게시글',
    zh: '文章',
    de: 'Artikel',
    fr: 'Articles',
    es: 'Artículos',
    ru: 'Статьи',
  },
  navBusiness: {
    ja: '事業内容',
    en: 'Business',
    ko: '사업 내용',
    zh: '业务内容',
    de: 'Geschäftsfelder',
    fr: 'Activités',
    es: 'Servicios',
    ru: 'Услуги',
  },
  navAbout: {
    ja: '私たちについて',
    en: 'Who we are',
    ko: '회사 소개',
    zh: '关于我们',
    de: 'Über uns',
    fr: 'Qui nous sommes',
    es: 'Quiénes somos',
    ru: 'Кто мы',
  },
  navContact: {
    ja: 'お問い合わせ',
    en: 'Contact',
    ko: '문의하기',
    zh: '联系我们',
    de: 'Kontakt',
    fr: 'Contact',
    es: 'Contacto',
    ru: 'Контакты',
  },

  // アクセシビリティ用のラベル
  skipToContent: {
    ja: 'メインコンテンツへスキップ',
    en: 'Skip to main content',
    ko: '본문으로 건너뛰기',
    zh: '跳到主要内容',
    de: 'Zum Hauptinhalt springen',
    fr: 'Aller au contenu principal',
    es: 'Saltar al contenido principal',
    ru: 'Перейти к основному содержанию',
  },
  navMain: {
    ja: 'メインメニュー',
    en: 'Main menu',
    ko: '메인 메뉴',
    zh: '主菜单',
    de: 'Hauptmenü',
    fr: 'Menu principal',
    es: 'Menú principal',
    ru: 'Главное меню',
  },
  navFooter: {
    ja: 'フッターメニュー',
    en: 'Footer menu',
    ko: '푸터 메뉴',
    zh: '页脚菜单',
    de: 'Fußzeilenmenü',
    fr: 'Menu de pied de page',
    es: 'Menú de pie de página',
    ru: 'Меню в подвале',
  },
  menuOpen: {
    ja: 'メニューを開く',
    en: 'Open menu',
    ko: '메뉴 열기',
    zh: '打开菜单',
    de: 'Menü öffnen',
    fr: 'Ouvrir le menu',
    es: 'Abrir el menú',
    ru: 'Открыть меню',
  },
  menuClose: {
    ja: 'メニューを閉じる',
    en: 'Close menu',
    ko: '메뉴 닫기',
    zh: '关闭菜单',
    de: 'Menü schließen',
    fr: 'Fermer le menu',
    es: 'Cerrar el menú',
    ru: 'Закрыть меню',
  },
  paginationLabel: {
    ja: 'ページ送り',
    en: 'Pagination',
    ko: '페이지 매김',
    zh: '分页',
    de: 'Seitennummerierung',
    fr: 'Pagination',
    es: 'Paginación',
    ru: 'Постраничная навигация',
  },
  paginationPage: {
    ja: '{n}ページ目',
    en: 'Page {n}',
    ko: '{n}페이지',
    zh: '第 {n} 页',
    de: 'Seite {n}',
    fr: 'Page {n}',
    es: 'Página {n}',
    ru: 'Страница {n}',
  },
  opensInNewTab: {
    ja: '（新しいタブで開く）',
    en: '(opens in a new tab)',
    ko: '(새 탭에서 열림)',
    zh: '（在新标签页中打开）',
    de: '(wird in einem neuen Tab geöffnet)',
    fr: '(ouvre dans un nouvel onglet)',
    es: '(se abre en una pestaña nueva)',
    ru: '(откроется в новой вкладке)',
  },

  // ヘッダーナビ（/hire-me。日本語のみ）
  navHireMe: { ja: '私を採用情報' },

  // フッター（法的ページのリンク。日本語のみ）
  navTerms: { ja: '利用規約' },
  navPrivacy: { ja: '個人情報保護方針' },
  // {year} は Footer 側で現在の年（new Date().getFullYear()）に置換する
  footerCopyright: {
    ja: '© {year} AXelWorks',
    en: '© {year} AXelWorks',
    ko: '© {year} AXelWorks',
    zh: '© {year} AXelWorks',
    de: '© {year} AXelWorks',
    fr: '© {year} AXelWorks',
    es: '© {year} AXelWorks',
    ru: '© {year} AXelWorks',
  },

  // News セクション（トップページの記事グリッド見出し・読み上げ文言）
  newsHeading: {
    ja: '記事',
    en: 'Articles',
    ko: '게시글',
    zh: '文章',
    de: 'Artikel',
    fr: 'Articles',
    es: 'Artículos',
    ru: 'Статьи',
  },
  // ニュース一覧ページ（/news, /news/p/N）の h1
  newsListHeading: {
    ja: '記事一覧',
    en: 'Articles',
    ko: '게시글 목록',
    zh: '文章列表',
    de: 'Artikel',
    fr: 'Articles',
    es: 'Artículos',
    ru: 'Статьи',
  },
  seeMore: {
    ja: 'もっとみる',
    en: 'See more',
    ko: '더 보기',
    zh: '查看更多',
    de: 'Mehr erfahren',
    fr: 'Voir plus',
    es: 'Ver más',
    ru: 'Подробнее',
  },
  newsListLink: {
    ja: '記事一覧へ',
    en: 'View all articles',
    ko: '게시글 목록 보기',
    zh: '查看全部文章',
    de: 'Alle Artikel ansehen',
    fr: 'Tous les articles',
    es: 'Ver todos los artículos',
    ru: 'Все статьи',
  },
  // トップページの記事グリッド「もっと見る」ボタン（読み込み中）
  loadMoreLoading: {
    ja: '読み込み中…',
    en: 'Loading…',
    ko: '불러오는 중…',
    zh: '正在加载…',
    de: 'Wird geladen …',
    fr: 'Chargement…',
    es: 'Cargando…',
    ru: 'Загрузка…',
  },
  // 取得失敗時のエラーメッセージ（下にボタンは残るので再度押せる旨は含めない）
  loadMoreError: {
    ja: '記事の読み込みに失敗しました。もう一度お試しください。',
    en: 'Failed to load more articles. Please try again.',
    ko: '기사를 불러오지 못했습니다. 다시 시도해 주세요.',
    zh: '加载文章失败，请重试。',
    de: 'Weitere Artikel konnten nicht geladen werden. Bitte versuchen Sie es erneut.',
    fr: 'Échec du chargement des articles. Veuillez réessayer.',
    es: 'No se pudieron cargar más artículos. Inténtelo de nuevo.',
    ru: 'Не удалось загрузить статьи. Повторите попытку.',
  },
  // 追加読み込み完了時の読み上げ用アナウンス（{n} は追加件数）
  loadMoreAnnouncement: {
    ja: '{n}件の記事を追加しました',
    en: 'Added {n} more articles',
    ko: '기사 {n}건을 추가했습니다',
    zh: '已添加 {n} 篇文章',
    de: '{n} weitere Artikel hinzugefügt',
    fr: '{n} articles supplémentaires ajoutés',
    es: 'Se añadieron {n} artículos más',
    ru: 'Добавлено ещё {n} статей',
  },

  // 記事詳細ページの目次
  tocHeading: {
    ja: '目次',
    en: 'Contents',
    ko: '목차',
    zh: '目录',
    de: 'Inhalt',
    fr: 'Sommaire',
    es: 'Índice',
    ru: 'Содержание',
  },

  // 下層ページのヒーローバナー小見出し（news はバナー廃止済み）
  businessPageHeading: {
    ja: '事業内容',
    en: 'Business',
    ko: '사업 내용',
    zh: '业务内容',
    de: 'Geschäftsfelder',
    fr: 'Activités',
    es: 'Servicios',
    ru: 'Услуги',
  },

  // ページ読み上げコントロール
  readAloudPlay: {
    ja: 'このページを読み上げる',
    en: 'Read this page aloud',
    ko: '이 페이지 읽어주기',
    zh: '朗读此页面',
    de: 'Diese Seite vorlesen',
    fr: 'Lire cette page à voix haute',
    es: 'Leer esta página en voz alta',
    ru: 'Озвучить эту страницу',
  },
  readAloudPause: {
    ja: '読み上げを一時停止',
    en: 'Pause reading',
    ko: '읽기 일시정지',
    zh: '暂停朗读',
    de: 'Vorlesen pausieren',
    fr: 'Suspendre la lecture',
    es: 'Pausar la lectura',
    ru: 'Приостановить озвучивание',
  },
  readAloudStop: {
    ja: '読み上げを停止',
    en: 'Stop reading',
    ko: '읽기 정지',
    zh: '停止朗读',
    de: 'Vorlesen stoppen',
    fr: 'Arrêter la lecture',
    es: 'Detener la lectura',
    ru: 'Остановить озвучивание',
  },
  readAloudSpeed: {
    ja: '速度',
    en: 'Speed',
    ko: '속도',
    zh: '速度',
    de: 'Tempo',
    fr: 'Vitesse',
    es: 'Velocidad',
    ru: 'Скорость',
  },
  // 「繰り返し」ボタン（停止中/未選択時のラベル。押すと回数を選ぶメニューが開く）
  readAloudRepeat: {
    ja: '繰り返す',
    en: 'Repeat',
    ko: '반복',
    zh: '重复',
    de: 'Wiederholen',
    fr: 'Répéter',
    es: 'Repetir',
    ru: 'Повторить',
  },
  // 「繰り返し」ボタン（繰り返し中のラベル。押すとメニューは開かず、今の周を
  // 最後まで読んだところで止まる）
  readAloudRepeatStop: {
    ja: '繰り返しを止める',
    en: 'Stop repeating',
    ko: '반복 중지',
    zh: '停止重复',
    de: 'Wiederholung stoppen',
    fr: 'Arrêter la répétition',
    es: 'Detener la repetición',
    ru: 'Остановить повтор',
  },
  // 繰り返し回数メニューの見出し（メニューの aria-label にも使う）
  readAloudRepeatMenuHeading: {
    ja: '繰り返す回数',
    en: 'Repeat count',
    ko: '반복 횟수',
    zh: '重复次数',
    de: 'Wiederholungsanzahl',
    fr: 'Nombre de répétitions',
    es: 'Número de repeticiones',
    ru: 'Количество повторов',
  },
  // 繰り返し回数メニューの各項目（{count} は REPEAT_OPTIONS の値に置換）
  readAloudRepeatOption: {
    ja: '{count}回',
    en: '{count} times',
    ko: '{count}회',
    zh: '{count} 次',
    de: '{count}-mal',
    fr: '{count} fois',
    es: '{count} veces',
    ru: '{count} раз',
  },
  // 繰り返し再生中の進行状況（aria-live で通知。読み上げ音声には含めない）
  readAloudRepeatProgress: {
    ja: '{lap}/{count}回目',
    en: 'Repeat {lap} of {count}',
    ko: '{lap}/{count}회째',
    zh: '第 {lap}/{count} 次',
    de: 'Wiederholung {lap} von {count}',
    fr: 'Répétition {lap} sur {count}',
    es: 'Repetición {lap} de {count}',
    ru: 'Повтор {lap} из {count}',
  },
  // 記事が長く音声キャッシュの上限を超えたため、繰り返し再生を無効化した旨の控えめな注記
  readAloudRepeatUnavailable: {
    ja: 'この記事は長いため「繰り返し」は利用できません',
    en: 'This article is too long for repeat playback.',
    ko: '이 글은 길어서 “반복”을 사용할 수 없습니다',
    zh: '这篇文章较长，无法使用“重复”功能',
    de: 'Dieser Artikel ist zu lang für die Wiederholungsfunktion.',
    fr: 'Cet article est trop long pour la lecture en boucle.',
    es: 'Este artículo es demasiado largo para la repetición.',
    ru: 'Эта статья слишком длинная для повтора воспроизведения.',
  },
  // /api/tts が失敗した（403/429/502等）ときの控えめなエラー表示。読み上げ対象の
  // テキストには含めず、aria-live での通知にのみ使う。
  readAloudError: {
    ja: '今は読み上げを使えません。しばらくしてからお試しください。',
    en: "Read-aloud isn't available right now. Please try again later.",
    ko: '지금은 읽어주기를 사용할 수 없습니다. 잠시 후 다시 시도해 주세요.',
    zh: '目前无法使用朗读功能，请稍后再试。',
    de: 'Das Vorlesen ist momentan nicht verfügbar. Bitte versuchen Sie es später erneut.',
    fr: "La lecture à voix haute n'est pas disponible pour le moment. Veuillez réessayer plus tard.",
    es: 'La lectura en voz alta no está disponible en este momento. Inténtelo de nuevo más tarde.',
    ru: 'Озвучивание сейчас недоступно. Повторите попытку позже.',
  },

  // 地球儀（言語切り替え）ボタンの aria-label。{lang} は選択中の言語の現地語名
  // （FLAGS の label、例: 日本語 / English）に置換する。
  globeLanguageSwitcherLabel: {
    ja: '現在の言語：{lang}。言語を変更',
    en: 'Current language: {lang}. Change language',
    ko: '현재 언어: {lang}. 언어 변경',
    zh: '当前语言：{lang}。更改语言',
    de: 'Aktuelle Sprache: {lang}. Sprache ändern',
    fr: 'Langue actuelle : {lang}. Changer de langue',
    es: 'Idioma actual: {lang}. Cambiar idioma',
    ru: 'Текущий язык: {lang}. Изменить язык',
  },
  // 言語選択メニュー（8言語の国旗リング）の aria-label
  globeLanguageMenuHeading: {
    ja: '言語を選択',
    en: 'Select language',
    ko: '언어 선택',
    zh: '选择语言',
    de: 'Sprache auswählen',
    fr: 'Choisir la langue',
    es: 'Seleccionar idioma',
    ru: 'Выбрать язык',
  },

  // ディクテーション練習モード（記事ページのみ）
  practiceEntryLabel: {
    ja: '練習',
    en: 'Practice',
    ko: '연습',
    zh: '练习',
    de: 'Übung',
    fr: 'Exercice',
    es: 'Práctica',
    ru: 'Практика',
  },
  practiceEntryAriaLabel: {
    ja: 'ディクテーション練習を開く',
    en: 'Open dictation practice',
    ko: '받아쓰기 연습 열기',
    zh: '打开听写练习',
    de: 'Diktat-Übung öffnen',
    fr: 'Ouvrir l’exercice de dictée',
    es: 'Abrir la práctica de dictado',
    ru: 'Открыть практику диктанта',
  },
  practicePanelHeading: {
    ja: 'ディクテーション練習',
    en: 'Dictation Practice',
    ko: '받아쓰기 연습',
    zh: '听写练习',
    de: 'Diktat-Übung',
    fr: 'Exercice de dictée',
    es: 'Práctica de dictado',
    ru: 'Практика диктанта',
  },
  practiceBoundaryLabel: {
    ja: '区切り',
    en: 'Break points',
    ko: '끊어 읽기 기준',
    zh: '停顿方式',
    de: 'Trennpunkte',
    fr: 'Points de pause',
    es: 'Puntos de pausa',
    ru: 'Точки паузы',
  },
  practiceBoundaryCommaPeriod: {
    ja: 'カンマ・ピリオド',
    en: 'Commas & periods',
    ko: '쉼표·마침표',
    zh: '逗号和句号',
    de: 'Kommas & Punkte',
    fr: 'Virgules et points',
    es: 'Comas y puntos',
    ru: 'Запятые и точки',
  },
  practiceBoundarySentence: {
    ja: '1文',
    en: 'Full sentences',
    ko: '문장 단위',
    zh: '整句',
    de: 'Ganze Sätze',
    fr: 'Phrases entières',
    es: 'Oraciones completas',
    ru: 'Целые предложения',
  },
  // 進み具合の表示（例: "3 / 42"）。{current} / {total} を置換する
  practiceProgress: {
    ja: '{current} / {total}',
    en: '{current} / {total}',
    ko: '{current} / {total}',
    zh: '{current} / {total}',
    de: '{current} / {total}',
    fr: '{current} / {total}',
    es: '{current} / {total}',
    ru: '{current} / {total}',
  },
  practiceRevealShow: {
    ja: '答えを見る',
    en: 'Show answer',
    ko: '정답 보기',
    zh: '查看答案',
    de: 'Antwort anzeigen',
    fr: 'Afficher la réponse',
    es: 'Ver la respuesta',
    ru: 'Показать ответ',
  },
  practiceRevealHide: {
    ja: '隠す',
    en: 'Hide',
    ko: '숨기기',
    zh: '隐藏',
    de: 'Verbergen',
    fr: 'Masquer',
    es: 'Ocultar',
    ru: 'Скрыть',
  },
  practiceHiddenNote: {
    ja: '紙に書き取ってから「答えを見る」を押してください',
    en: 'Write it down on paper, then tap "Show answer"',
    ko: '종이에 받아쓴 다음 "정답 보기"를 눌러 주세요',
    zh: '请先在纸上写下来，再点击"查看答案"',
    de: 'Schreiben Sie es zuerst auf Papier, dann auf „Antwort anzeigen" tippen',
    fr: 'Écrivez-le sur papier, puis appuyez sur « Afficher la réponse »',
    es: 'Escríbalo en papel y luego pulse "Ver la respuesta"',
    ru: 'Запишите на бумаге, затем нажмите «Показать ответ»',
  },
  practiceStart: {
    ja: '開始',
    en: 'Start',
    ko: '시작',
    zh: '开始',
    de: 'Start',
    fr: 'Démarrer',
    es: 'Empezar',
    ru: 'Начать',
  },
  practiceReplay: {
    ja: 'もう一度',
    en: 'Replay',
    ko: '다시 듣기',
    zh: '再听一次',
    de: 'Wiederholen',
    fr: 'Réécouter',
    es: 'Repetir',
    ru: 'Ещё раз',
  },
  practiceNext: {
    ja: '次へ',
    en: 'Next',
    ko: '다음',
    zh: '下一句',
    de: 'Weiter',
    fr: 'Suivant',
    es: 'Siguiente',
    ru: 'Далее',
  },
  practicePrevious: {
    ja: '前へ',
    en: 'Previous',
    ko: '이전',
    zh: '上一句',
    de: 'Zurück',
    fr: 'Précédent',
    es: 'Anterior',
    ru: 'Назад',
  },
  practiceFinish: {
    ja: '終了',
    en: 'Finish',
    ko: '종료',
    zh: '结束',
    de: 'Beenden',
    fr: 'Terminer',
    es: 'Finalizar',
    ru: 'Завершить',
  },
  practiceFinishedHeading: {
    ja: 'おわりました',
    en: 'All done!',
    ko: '모두 끝났습니다',
    zh: '已完成',
    de: 'Geschafft!',
    fr: 'Terminé !',
    es: '¡Completado!',
    ru: 'Готово!',
  },
  practiceRestart: {
    ja: '最初から',
    en: 'Start over',
    ko: '처음부터',
    zh: '从头开始',
    de: 'Von vorn beginnen',
    fr: 'Recommencer',
    es: 'Empezar de nuevo',
    ru: 'Начать сначала',
  },
  // 練習の種類（手書き／リピート再生）を選ぶ2択の見出し・aria-label
  practiceTypeLabel: {
    ja: '練習の種類',
    en: 'Practice type',
    ko: '연습 종류',
    zh: '练习类型',
    de: 'Übungsart',
    fr: "Type d'exercice",
    es: 'Tipo de práctica',
    ru: 'Тип практики',
  },
  practiceTypeDictation: {
    ja: '手書き',
    en: 'Handwriting',
    ko: '손으로 쓰기',
    zh: '手写',
    de: 'Handschrift',
    fr: 'Écriture manuscrite',
    es: 'Escritura a mano',
    ru: 'Письмо от руки',
  },
  // 既存の繰り返し機能の英語表記「Repeat」とは区別する（区間ごとに自動で
  // 進み続ける「リピート再生」練習モード）
  practiceTypeRepeat: {
    ja: 'リピート再生',
    en: 'Repeating',
    ko: '반복 재생',
    zh: '循环播放',
    de: 'Wiederholtes Abspielen',
    fr: 'Lecture en boucle',
    es: 'Reproducción en bucle',
    ru: 'Повторное воспроизведение',
  },
  // リピート再生専用のボタン（自動で進むのを一時的に止める・続きから再開する）
  practicePause: {
    ja: '一時停止',
    en: 'Pause',
    ko: '일시정지',
    zh: '暂停',
    de: 'Pause',
    fr: 'Pause',
    es: 'Pausa',
    ru: 'Пауза',
  },
  practiceResume: {
    ja: '再開',
    en: 'Resume',
    ko: '재개',
    zh: '继续',
    de: 'Fortsetzen',
    fr: 'Reprendre',
    es: 'Reanudar',
    ru: 'Продолжить',
  },

  // Business セクション
  businessHeading: { ja: 'Business' },
  businessSubtitle: {
    ja: '事業内容',
    en: 'Our business',
    ko: '사업 소개',
    zh: '业务介绍',
    de: 'Unser Angebot',
    fr: 'Notre activité',
    es: 'Nuestra actividad',
    ru: 'Наша деятельность',
  },
  businessBody1: {
    ja: '当社は、次世代テクノロジーの研究開発・製造・販売を行う革新的な企業です。',
    en: 'We are an innovative company engaged in the research, development, manufacturing, and sales of next-generation technology.',
    ko: '당사는 차세대 기술의 연구개발·제조·판매를 하는 혁신적인 기업입니다.',
    zh: '我们是一家从事新一代技术研发、制造与销售的创新型企业。',
    de: 'Wir sind ein innovatives Unternehmen für Forschung, Entwicklung, Fertigung und Vertrieb von Technologien der nächsten Generation.',
    fr: 'Nous sommes une entreprise innovante spécialisée dans la recherche, le développement, la fabrication et la commercialisation de technologies de nouvelle génération.',
    es: 'Somos una empresa innovadora dedicada a la investigación, el desarrollo, la fabricación y la venta de tecnología de nueva generación.',
    ru: 'Мы — инновационная компания, занимающаяся исследованиями, разработкой, производством и продажей технологий нового поколения.',
  },
  businessBody2: {
    ja: 'AI、ロボット工学、自律システムなど、幅広い分野でのソリューション提供を通じて、社会の進化と未来の創造に貢献します。',
    en: 'Through solutions across a wide range of fields — AI, robotics, autonomous systems and more — we contribute to the advancement of society and the creation of the future.',
    ko: 'AI, 로보틱스, 자율 시스템 등 폭넓은 분야에서 솔루션을 제공하며, 사회의 발전과 미래 창조에 기여합니다.',
    zh: '我们通过在人工智能、机器人工程、自主系统等广泛领域提供解决方案，助力社会进步与未来创造。',
    de: 'Mit Lösungen in vielfältigen Bereichen – KI, Robotik, autonome Systeme und mehr – tragen wir zum Fortschritt der Gesellschaft und zur Gestaltung der Zukunft bei.',
    fr: "Grâce à des solutions dans de nombreux domaines — IA, robotique, systèmes autonomes et bien d'autres —, nous contribuons au progrès de la société et à la construction de l'avenir.",
    es: 'A través de soluciones en una amplia variedad de campos —IA, robótica, sistemas autónomos y más—, contribuimos al avance de la sociedad y a la creación del futuro.',
    ru: 'Предлагая решения в самых разных областях — искусственный интеллект, робототехника, автономные системы и многое другое, — мы вносим вклад в развитие общества и создание будущего.',
  },

  // About Us セクション
  aboutHeading: { ja: 'About Us' },
  aboutSubtitle: {
    ja: '私たちについて',
    en: 'Who we are',
    ko: '회사 소개',
    zh: '关于我们',
    de: 'Über uns',
    fr: 'Qui nous sommes',
    es: 'Quiénes somos',
    ru: 'Кто мы',
  },
  // トップページの要約。全文は /company ページ
  aboutLead: {
    ja: '社員は一人。でも、仕事は一人でやらない。',
    en: 'One employee. But no one here works alone.',
    ko: '직원은 한 명. 하지만 일은 혼자 하지 않습니다.',
    zh: '员工只有一人，但工作从不独自完成。',
    de: 'Ein Mitarbeiter. Aber hier arbeitet niemand allein.',
    fr: 'Un seul employé. Mais personne ne travaille seul ici.',
    es: 'Un solo empleado. Pero aquí nadie trabaja solo.',
    ru: 'Один сотрудник. Но здесь никто не работает в одиночку.',
  },
  aboutSummary: {
    ja: 'AIと人がお互いの得意で働き、企業の「面倒」を減らすアプリと、人の「学びたい」を後押しするアプリをつくっています。',
    en: 'People and AI each play to their strengths, building apps that cut business busywork and apps that back people who want to learn.',
    ko: 'AI와 사람이 각자의 강점을 살려, 기업의 ‘번거로움’을 줄이는 앱과 사람의 ‘배우고 싶다’를 돕는 앱을 만듭니다.',
    zh: 'AI 与人各展所长，打造为企业减少繁琐事务的应用，以及支持人们求知的应用。',
    de: 'Mensch und KI bringen jeweils ihre Stärken ein und entwickeln Apps, die Unternehmen lästige Arbeit ersparen, und Apps, die Lernwillige unterstützen.',
    fr: "L'humain et l'IA jouent chacun de leurs forces pour créer des applications qui allègent les corvées des entreprises et d'autres qui soutiennent celles et ceux qui veulent apprendre.",
    es: 'Las personas y la IA aportan cada una sus fortalezas para crear aplicaciones que reducen las tareas tediosas de las empresas y otras que apoyan a quienes quieren aprender.',
    ru: 'Человек и ИИ используют свои сильные стороны и создают приложения, которые избавляют бизнес от рутины, и приложения для тех, кто хочет учиться.',
  },

  // トップページの「私を採用情報」誘導セクション（/hire-me へ）。
  // 「私を採用情報」は日本語の言葉遊びのため subtitle / body / link は日本語のみ。
  hireMeHeading: { ja: 'Hire me' },
  hireMeSubtitle: { ja: '私を採用情報' },
  hireMeBody1: {
    ja: '「採用情報」という言葉ですが、このページで採用されようとしているのは私です。受託でも、雇用でも、私と、一緒に働くAIエージェントたちを、あなたの仕事に組み込んでみませんか。',
  },
  hireMeBody2: {
    ja: '39年のIT業界での経験と、AIエージェントとの新しい働き方について、詳しくご紹介しています。',
  },
  hireMeLink: {
    ja: '私を採用情報へ',
  },

  // 事業内容ページ末尾の問い合わせ誘導セクション（トップの商談予約フォームへ遷移）
  businessContactHeading: {
    ja: 'お問い合わせ',
    en: 'Contact',
    ko: '문의하기',
    zh: '联系我们',
    de: 'Kontakt',
    fr: 'Contact',
    es: 'Contacto',
    ru: 'Связаться с нами',
  },
  businessContactBody: {
    ja: 'ご相談・お見積もりなど、お気軽にお問い合わせください。',
    en: 'Questions, estimates, or an idea to talk through — feel free to get in touch.',
    ko: '상담·견적 등 무엇이든 편하게 문의해 주세요.',
    zh: '咨询、报价或任何想法，都欢迎随时与我们联系。',
    de: 'Ob Beratung, Kostenvoranschlag oder erste Idee – kontaktieren Sie uns gern.',
    fr: 'Questions, devis ou simple idée à échanger : n’hésitez pas à nous contacter.',
    es: 'Consultas, presupuestos o cualquier idea que quiera comentar: escríbanos sin compromiso.',
    ru: 'Консультация, смета или просто идея для обсуждения — напишите нам.',
  },
  businessContactLink: {
    ja: 'お問い合わせフォームへ',
    en: 'Go to the contact form',
    ko: '문의 폼으로 이동',
    zh: '前往咨询表单',
    de: 'Zum Kontaktformular',
    fr: 'Accéder au formulaire de contact',
    es: 'Ir al formulario de contacto',
    ru: 'Перейти к форме обращения',
  },

  // ----- Contact セクション（左カラム） -----
  contactEyebrow: { ja: 'CONTACT' },
  contactHeadingLead: {
    ja: 'その「ちょっと困った」、',
    en: 'That "I\'m a little stuck" —',
    ko: '그 “조금 곤란한 일”,',
    zh: '你那点“小小的烦恼”，',
    de: 'Ihr „kleines Problem“ –',
    fr: 'Ce petit « souci » qui vous bloque,',
    es: 'Ese pequeño «problema» que le frena,',
    ru: 'Та самая «небольшая загвоздка»,',
  },
  contactHeadingAccent: {
    ja: '聞かせてください。',
    en: "let's talk it through.",
    ko: '들려주세요.',
    zh: '说给我们听听吧。',
    de: 'erzählen Sie es uns.',
    fr: 'parlons-en ensemble.',
    es: 'cuéntenoslo.',
    ru: 'расскажите нам о ней.',
  },
  contactLead1: {
    ja: 'まだアイデアが固まっていなくても大丈夫です。',
    en: "It's fine if your idea isn't fully formed yet.",
    ko: '아직 아이디어가 명확하지 않아도 괜찮습니다.',
    zh: '即使想法尚未成型也没关系。',
    de: 'Es macht nichts, wenn Ihre Idee noch nicht ausgereift ist.',
    fr: "Peu importe si votre idée n'est pas encore aboutie.",
    es: 'No pasa nada si su idea aún no está del todo definida.',
    ru: 'Ничего страшного, если ваша идея ещё не оформилась.',
  },
  contactLead2: {
    ja: 'できることから、一緒に考えます。',
    en: "We'll figure out the next step together.",
    ko: '할 수 있는 것부터 함께 고민하겠습니다.',
    zh: '我们会从力所能及之处，与你一起思考。',
    de: 'Wir überlegen gemeinsam den nächsten Schritt.',
    fr: 'Nous réfléchirons ensemble à la prochaine étape.',
    es: 'Pensaremos juntos en el siguiente paso.',
    ru: 'Вместе подумаем над следующим шагом.',
  },
  contactService1: {
    ja: 'AIエージェント実装支援（法人向けコンサルティング）',
    en: 'AI agent implementation support (consulting for businesses)',
    ko: 'AI 에이전트 구축 지원(법인 대상 컨설팅)',
    zh: 'AI 智能体落地支持（面向企业的咨询）',
    de: 'Unterstützung bei der Einführung von KI-Agenten (Beratung für Unternehmen)',
    fr: "Accompagnement à la mise en œuvre d'agents IA (conseil aux entreprises)",
    es: 'Apoyo en la implementación de agentes de IA (consultoría para empresas)',
    ru: 'Поддержка внедрения ИИ-агентов (консалтинг для компаний)',
  },
  contactService2: {
    ja: '受託開発・SaaS開発',
    en: 'Contract development & SaaS development',
    ko: '수탁 개발·SaaS 개발',
    zh: '受托开发·SaaS 开发',
    de: 'Auftragsentwicklung & SaaS-Entwicklung',
    fr: 'Développement sur mesure et développement SaaS',
    es: 'Desarrollo por encargo y desarrollo SaaS',
    ru: 'Разработка на заказ и разработка SaaS',
  },
  contactService3: {
    ja: 'AI・IT研修事業「AX Academy」',
    en: 'AI & IT training — "AX Academy"',
    ko: 'AI·IT 교육 사업 ‘AX Academy’',
    zh: 'AI·IT 培训业务“AX Academy”',
    de: 'KI- und IT-Schulungen – „AX Academy“',
    fr: 'Formations IA et IT « AX Academy »',
    es: 'Formación en IA e IT «AX Academy»',
    ru: 'Обучение ИИ и ИТ «AX Academy»',
  },

  // ----- Contact フォーム -----
  formName: {
    ja: 'お名前',
    en: 'Name',
    ko: '이름',
    zh: '姓名',
    de: 'Name',
    fr: 'Nom',
    es: 'Nombre',
    ru: 'Имя',
  },
  formNamePlaceholder: {
    ja: '山田 太郎',
    en: 'Jane Doe',
    ko: '홍길동',
    zh: '张三',
    de: 'Max Mustermann',
    fr: 'Jean Dupont',
    es: 'Juan Pérez',
    ru: 'Иван Иванов',
  },
  formEmail: {
    ja: 'メールアドレス',
    en: 'Email',
    ko: '이메일 주소',
    zh: '电子邮箱',
    de: 'E-Mail-Adresse',
    fr: 'Adresse e-mail',
    es: 'Correo electrónico',
    ru: 'Электронная почта',
  },
  formConsultation: {
    ja: 'ご相談内容',
    en: 'What would you like to discuss?',
    ko: '문의 내용',
    zh: '咨询内容',
    de: 'Worum geht es?',
    fr: 'Votre demande',
    es: '¿Sobre qué desea hablar?',
    ru: 'Ваш запрос',
  },
  formConsultationPlaceholder: {
    ja: '選択してください',
    en: 'Please select',
    ko: '선택해 주세요',
    zh: '请选择',
    de: 'Bitte wählen',
    fr: 'Sélectionnez',
    es: 'Seleccione una opción',
    ru: 'Выберите',
  },
  formMessage: {
    ja: 'メッセージ',
    en: 'Message',
    ko: '메시지',
    zh: '留言',
    de: 'Nachricht',
    fr: 'Message',
    es: 'Mensaje',
    ru: 'Сообщение',
  },
  formMessagePlaceholder: {
    ja: 'まだぼんやりした内容でも、お気軽にどうぞ。',
    en: 'Even a rough idea is fine — feel free to write.',
    ko: '아직 막연한 내용이라도 편하게 남겨 주세요.',
    zh: '即使还只是模糊的想法，也请随意填写。',
    de: 'Auch eine grobe Idee genügt – schreiben Sie einfach.',
    fr: 'Même une idée encore vague suffit — écrivez-nous librement.',
    es: 'Aunque sea una idea aún vaga, escríbanos sin problema.',
    ru: 'Даже если идея пока размытая, пишите смело.',
  },
  formRequired: {
    ja: '必須',
    en: 'Required',
    ko: '필수',
    zh: '必填',
    de: 'Pflichtfeld',
    fr: 'Obligatoire',
    es: 'Obligatorio',
    ru: 'Обязательно',
  },
  formOptional: {
    ja: '任意',
    en: 'Optional',
    ko: '선택',
    zh: '选填',
    de: 'Optional',
    fr: 'Facultatif',
    es: 'Opcional',
    ru: 'Необязательно',
  },
  formCalendarLegend: {
    ja: 'Google Meet相談（顔出し不要）の候補日時を選択してください（最大{max}件）',
    en: 'Choose up to {max} preferred times for a Google Meet call (camera optional)',
    ko: 'Google Meet 상담(얼굴 공개 불필요) 희망 일시를 선택해 주세요(최대 {max}건)',
    zh: '请选择 Google Meet 咨询（无需露脸）的候选日期时间（最多 {max} 个）',
    de: 'Wählen Sie bis zu {max} Wunschtermine für ein Google-Meet-Gespräch (Kamera optional)',
    fr: "Choisissez jusqu'à {max} créneaux pour un échange sur Google Meet (caméra facultative)",
    es: 'Elija hasta {max} horarios para una reunión por Google Meet (cámara opcional)',
    ru: 'Выберите до {max} вариантов даты и времени для встречи в Google Meet (камера по желанию)',
  },
  formCalendarNote: {
    ja: '直近の営業日から自動で3日分表示しています',
    en: 'Showing the next 3 business days automatically',
    ko: '가장 가까운 영업일부터 자동으로 3일치를 표시합니다',
    zh: '自动显示从最近工作日起的 3 天',
    de: 'Es werden automatisch die nächsten 3 Werktage angezeigt',
    fr: "Les 3 prochains jours ouvrés s'affichent automatiquement",
    es: 'Se muestran automáticamente los próximos 3 días hábiles',
    ru: 'Автоматически показаны ближайшие 3 рабочих дня',
  },
  formTimeColumn: {
    ja: '時間帯',
    en: 'Time',
    ko: '시간대',
    zh: '时间段',
    de: 'Uhrzeit',
    fr: 'Horaire',
    es: 'Franja horaria',
    ru: 'Время',
  },
  formSlotClosed: {
    ja: '（受付終了）',
    en: '(closed)',
    ko: '(마감)',
    zh: '（已截止）',
    de: '(geschlossen)',
    fr: '(clôturé)',
    es: '(cerrado)',
    ru: '(приём закрыт)',
  },
  formSlotsCounter: {
    ja: '{n} / {max}件選択中',
    en: '{n} of {max} selected',
    ko: '{n} / {max}건 선택 중',
    zh: '已选择 {n} / {max} 个',
    de: '{n} von {max} ausgewählt',
    fr: '{n} / {max} sélectionné(s)',
    es: '{n} / {max} seleccionados',
    ru: 'Выбрано {n} / {max}',
  },
  formSubmit: {
    ja: '相談内容を送る',
    en: 'Send message',
    ko: '상담 내용 보내기',
    zh: '发送咨询内容',
    de: 'Nachricht senden',
    fr: 'Envoyer le message',
    es: 'Enviar mensaje',
    ru: 'Отправить сообщение',
  },
  formSubmitting: {
    ja: '送信中…',
    en: 'Sending…',
    ko: '전송 중…',
    zh: '发送中…',
    de: 'Wird gesendet…',
    fr: 'Envoi en cours…',
    es: 'Enviando…',
    ru: 'Отправка…',
  },
  formSubmitNote: {
    ja: '入力内容と選択した候補日時を、担当者へメールで送信します。',
    en: 'Your details and selected times will be emailed to our team.',
    ko: '입력하신 내용과 선택한 희망 일시를 담당자에게 이메일로 전송합니다.',
    zh: '您填写的内容和所选候选时间将通过邮件发送给我们的负责人。',
    de: 'Ihre Angaben und die gewählten Termine werden per E-Mail an unser Team gesendet.',
    fr: 'Vos informations et les créneaux choisis seront transmis par e-mail à notre équipe.',
    es: 'Sus datos y los horarios seleccionados se enviarán por correo a nuestro equipo.',
    ru: 'Ваши данные и выбранные варианты времени будут отправлены нашей команде по электронной почте.',
  },
  formSuccessTitle: {
    ja: '送信しました。ありがとうございます。',
    en: 'Sent — thank you!',
    ko: '전송되었습니다. 감사합니다.',
    zh: '已发送，谢谢您！',
    de: 'Gesendet – vielen Dank!',
    fr: 'Envoyé – merci !',
    es: 'Enviado. ¡Gracias!',
    ru: 'Отправлено. Спасибо!',
  },
  formSuccessBody: {
    ja: '担当者が内容を確認のうえ、いただいたメールアドレス宛に日程のご連絡をいたします。通常2〜3営業日以内にご返信します。',
    en: 'Our team will review your message and email you to arrange a time, usually within 2–3 business days.',
    ko: '담당자가 내용을 확인한 후, 남겨 주신 이메일 주소로 일정을 안내해 드립니다. 보통 2~3영업일 이내에 답변드립니다.',
    zh: '我们的负责人确认内容后，会通过您提供的邮箱与您联系确定日程。通常在 2～3 个工作日内回复。',
    de: 'Unser Team prüft Ihre Nachricht und meldet sich per E-Mail zur Terminabstimmung – in der Regel innerhalb von 2–3 Werktagen.',
    fr: "Notre équipe examinera votre message et vous écrira par e-mail pour convenir d'un rendez-vous, généralement sous 2 à 3 jours ouvrés.",
    es: 'Nuestro equipo revisará su mensaje y le escribirá por correo para concertar una cita, normalmente en un plazo de 2 a 3 días hábiles.',
    ru: 'Наша команда рассмотрит ваше сообщение и напишет вам на указанный адрес электронной почты, чтобы согласовать время — обычно в течение 2–3 рабочих дней.',
  },

  // ご相談内容の選択肢
  consultAgent: {
    ja: 'AIエージェント実装相談',
    en: 'AI agent implementation',
    ko: 'AI 에이전트 구축 상담',
    zh: 'AI 智能体落地咨询',
    de: 'Einführung von KI-Agenten',
    fr: "Mise en œuvre d'agents IA",
    es: 'Implementación de agentes de IA',
    ru: 'Внедрение ИИ-агентов',
  },
  consultDev: {
    ja: '受託開発・SaaS開発相談',
    en: 'Contract / SaaS development',
    ko: '수탁 개발·SaaS 개발 상담',
    zh: '受托开发·SaaS 开发咨询',
    de: 'Auftrags- / SaaS-Entwicklung',
    fr: 'Développement sur mesure / SaaS',
    es: 'Desarrollo por encargo / SaaS',
    ru: 'Разработка на заказ / SaaS',
  },
  consultTraining: {
    ja: 'AI・IT研修相談（AX Academy）',
    en: 'AI & IT training (AX Academy)',
    ko: 'AI·IT 교육 상담(AX Academy)',
    zh: 'AI·IT 培训咨询（AX Academy）',
    de: 'KI- & IT-Schulungen (AX Academy)',
    fr: 'Formations IA et IT (AX Academy)',
    es: 'Formación en IA e IT (AX Academy)',
    ru: 'Обучение ИИ и ИТ (AX Academy)',
  },
  consultOther: {
    ja: 'その他',
    en: 'Other',
    ko: '기타',
    zh: '其他',
    de: 'Sonstiges',
    fr: 'Autre',
    es: 'Otro',
    ru: 'Другое',
  },

  // バリデーションエラー
  errNameRequired: {
    ja: 'お名前を入力してください',
    en: 'Please enter your name.',
    ko: '이름을 입력해 주세요',
    zh: '请输入您的姓名',
    de: 'Bitte geben Sie Ihren Namen ein.',
    fr: 'Veuillez saisir votre nom.',
    es: 'Introduzca su nombre.',
    ru: 'Введите ваше имя.',
  },
  errEmailRequired: {
    ja: 'メールアドレスを入力してください',
    en: 'Please enter your email address.',
    ko: '이메일 주소를 입력해 주세요',
    zh: '请输入电子邮箱',
    de: 'Bitte geben Sie Ihre E-Mail-Adresse ein.',
    fr: 'Veuillez saisir votre adresse e-mail.',
    es: 'Introduzca su correo electrónico.',
    ru: 'Введите адрес электронной почты.',
  },
  errEmailInvalid: {
    ja: 'メールアドレスの形式が正しくありません',
    en: 'Please enter a valid email address.',
    ko: '이메일 주소 형식이 올바르지 않습니다',
    zh: '电子邮箱格式不正确',
    de: 'Bitte geben Sie eine gültige E-Mail-Adresse ein.',
    fr: 'Veuillez saisir une adresse e-mail valide.',
    es: 'Introduzca un correo electrónico válido.',
    ru: 'Введите корректный адрес электронной почты.',
  },
  errConsultationRequired: {
    ja: 'ご相談内容を選択してください',
    en: 'Please select a topic.',
    ko: '문의 내용을 선택해 주세요',
    zh: '请选择咨询内容',
    de: 'Bitte wählen Sie ein Thema.',
    fr: 'Veuillez sélectionner un sujet.',
    es: 'Seleccione un tema.',
    ru: 'Выберите тему.',
  },
  errSlotsRequired: {
    ja: '候補日時を1件以上選択してください',
    en: 'Please select at least one time slot.',
    ko: '희망 일시를 1건 이상 선택해 주세요',
    zh: '请至少选择一个候选时间',
    de: 'Bitte wählen Sie mindestens einen Termin.',
    fr: 'Veuillez sélectionner au moins un créneau.',
    es: 'Seleccione al menos un horario.',
    ru: 'Выберите хотя бы один вариант времени.',
  },
  errSubmitFailed: {
    ja: '送信に失敗しました。お手数ですが時間をおいて再度お試しいただくか、直接メールにてご連絡ください。',
    en: 'Something went wrong. Please try again later, or contact us directly by email.',
    ko: '전송에 실패했습니다. 번거로우시겠지만 잠시 후 다시 시도하시거나, 이메일로 직접 연락해 주세요.',
    zh: '发送失败。请稍后重试，或直接通过邮件与我们联系。',
    de: 'Etwas ist schiefgelaufen. Bitte versuchen Sie es später erneut oder kontaktieren Sie uns direkt per E-Mail.',
    fr: "Une erreur s'est produite. Veuillez réessayer plus tard ou nous contacter directement par e-mail.",
    es: 'Se ha producido un error. Vuelva a intentarlo más tarde o contáctenos directamente por correo.',
    ru: 'Произошла ошибка. Повторите попытку позже или свяжитесь с нами напрямую по электронной почте.',
  },
  errNetwork: {
    ja: 'ネットワークエラーにより送信できませんでした。通信環境をご確認のうえ再度お試しください。',
    en: "Couldn't send due to a network error. Please check your connection and try again.",
    ko: '네트워크 오류로 전송하지 못했습니다. 통신 환경을 확인하신 후 다시 시도해 주세요.',
    zh: '因网络错误未能发送。请检查网络连接后重试。',
    de: 'Aufgrund eines Netzwerkfehlers konnte nicht gesendet werden. Bitte prüfen Sie Ihre Verbindung und versuchen Sie es erneut.',
    fr: "L'envoi a échoué en raison d'une erreur réseau. Veuillez vérifier votre connexion et réessayer.",
    es: 'No se pudo enviar debido a un error de red. Compruebe su conexión e inténtelo de nuevo.',
    ru: 'Не удалось отправить из-за сетевой ошибки. Проверьте подключение и повторите попытку.',
  },
  errNotConfigured: {
    ja: '送信設定が未完了のため送信できませんでした。お手数ですが時間をおいて再度お試しください。',
    en: "The form isn't fully configured yet. Please try again later.",
    ko: '전송 설정이 완료되지 않아 전송하지 못했습니다. 번거로우시겠지만 잠시 후 다시 시도해 주세요.',
    zh: '由于发送设置尚未完成，未能发送。请稍后重试。',
    de: 'Das Formular ist noch nicht vollständig konfiguriert. Bitte versuchen Sie es später erneut.',
    fr: "Le formulaire n'est pas encore entièrement configuré. Veuillez réessayer plus tard.",
    es: 'El formulario aún no está del todo configurado. Vuelva a intentarlo más tarde.',
    ru: 'Форма ещё не полностью настроена. Повторите попытку позже.',
  },

  // SaaS開発ページ（/saas）
  navSaas: {
    ja: 'SaaS開発',
    en: 'SaaS Development',
    ko: 'SaaS 개발',
    zh: 'SaaS 开发',
    de: 'SaaS-Entwicklung',
    fr: 'Développement SaaS',
    es: 'Desarrollo SaaS',
    ru: 'Разработка SaaS',
  },
  // /saas・/navi-lp の見出し付近に置く「事業内容に戻る」リンク（ヘッダーが使えない場合の保険）
  backToBusinessLabel: {
    ja: '← 事業内容に戻る',
    en: '← Back to Business',
    ko: '← 사업 내용으로 돌아가기',
    zh: '← 返回业务内容',
    de: '← Zurück zu den Geschäftsfeldern',
    fr: '← Retour aux activités',
    es: '← Volver a Servicios',
    ru: '← Назад к Услугам',
  },
  saasHeading: {
    ja: 'SaaS開発',
    en: 'SaaS Development',
    ko: 'SaaS 개발',
    zh: 'SaaS 开发',
    de: 'SaaS-Entwicklung',
    fr: 'Développement SaaS',
    es: 'Desarrollo SaaS',
    ru: 'Разработка SaaS',
  },
  saasLead: {
    ja: '自分のnoteのデータで動く、マルチテナント型のSaaS「noteAnalytics」を、AIと一緒に作っています。',
    en: "I'm building noteAnalytics, a multi-tenant SaaS powered by my own note data, together with AI.",
    ko: '제 note 데이터로 동작하는 멀티테넌트형 SaaS ‘noteAnalytics’를 AI와 함께 만들고 있습니다.',
    zh: '我正在与 AI 一起开发基于我自己 note 数据运行的多租户 SaaS「noteAnalytics」。',
    de: 'Gemeinsam mit KI entwickle ich noteAnalytics, ein Multi-Tenant-SaaS, das mit meinen eigenen note-Daten arbeitet.',
    fr: "Je développe, avec l'aide de l'IA, noteAnalytics, un SaaS multi-tenant qui fonctionne avec mes propres données note.",
    es: 'Estoy creando, junto con la IA, noteAnalytics, un SaaS multiinquilino que funciona con mis propios datos de note.',
    ru: 'Вместе с ИИ я разрабатываю noteAnalytics — мультитенантный SaaS, работающий на основе моих собственных данных note.',
  },
  saasBuildingHeading: {
    ja: '作っているもの',
    en: "What I'm building",
    ko: '만들고 있는 것',
    zh: '正在开发的内容',
    de: 'Was ich entwickle',
    fr: 'Ce que je développe',
    es: 'Lo que estoy creando',
    ru: 'Что я разрабатываю',
  },
  saasBuildingBody: {
    ja: 'noteのフォロワー数、スキ・フォロー・コメントなどのデータを集めて、1つのダッシュボードで見られるWebシステムです。複数のアカウントを、まとめて見ることができます。',
    en: 'A web system that gathers note data — follower counts, likes, follows, and comments — into a single dashboard. You can view multiple accounts together.',
    ko: 'note의 팔로워 수, 좋아요·팔로우·댓글 등의 데이터를 모아 하나의 대시보드에서 볼 수 있는 웹 시스템입니다. 여러 계정을 한꺼번에 볼 수 있습니다.',
    zh: '这是一套汇总 note 的粉丝数、点赞、关注、评论等数据，并在同一个仪表盘中查看的网页系统。可以同时查看多个账号。',
    de: 'Ein Websystem, das note-Daten – Follower-Zahlen, Likes, Follows und Kommentare – in einem einzigen Dashboard zusammenführt. Mehrere Konten lassen sich gemeinsam anzeigen.',
    fr: "Un système web qui rassemble les données note (nombre d'abonnés, likes, follows, commentaires) dans un tableau de bord unique. Plusieurs comptes peuvent être consultés ensemble.",
    es: 'Un sistema web que reúne los datos de note —número de seguidores, me gusta, seguimientos y comentarios— en un único panel. Se pueden ver varias cuentas a la vez.',
    ru: 'Веб-система, которая собирает данные note — число подписчиков, лайки, подписки и комментарии — в единой панели. Несколько аккаунтов можно просматривать вместе.',
  },
  saasScreensHeading: {
    ja: '主な画面',
    en: 'Main screens',
    ko: '주요 화면',
    zh: '主要页面',
    de: 'Hauptansichten',
    fr: 'Écrans principaux',
    es: 'Pantallas principales',
    ru: 'Основные экраны',
  },
  saasScreenYojitsuTitle: {
    ja: '予実管理',
    en: 'Target vs. actual',
    ko: '목표 대비 실적',
    zh: '目标与实际',
    de: 'Soll-Ist-Vergleich',
    fr: 'Suivi objectifs / réalisé',
    es: 'Objetivo frente a real',
    ru: 'План/факт',
  },
  saasScreenYojitsuDesc: {
    ja: '月ごとのフォロワー数の目標と実績を、複合グラフで見ます。',
    en: "See each month's follower target and actual numbers in a combo chart.",
    ko: '월별 팔로워 수의 목표와 실적을 복합 그래프로 봅니다.',
    zh: '通过复合图表查看每月粉丝数的目标与实际情况。',
    de: 'Monatliches Follower-Ziel und tatsächlicher Wert in einem Kombi-Diagramm.',
    fr: "Visualisez l'objectif et le résultat mensuels d'abonnés dans un graphique combiné.",
    es: 'Vea el objetivo y el resultado mensual de seguidores en un gráfico combinado.',
    ru: 'Ежемесячная цель и фактическое число подписчиков на комбинированной диаграмме.',
  },
  saasScreenFollowerTitle: {
    ja: 'フォロワー数',
    en: 'Follower count',
    ko: '팔로워 수',
    zh: '粉丝数',
    de: 'Followerzahl',
    fr: "Nombre d'abonnés",
    es: 'Número de seguidores',
    ru: 'Число подписчиков',
  },
  saasScreenFollowerDesc: {
    ja: 'アカウントごとの日別の推移を、年・月で絞り込んで見ます。',
    en: "View each account's daily trend, filtered by year and month.",
    ko: '계정별 일별 추이를 연도·월로 좁혀서 봅니다.',
    zh: '按年、月筛选，查看各账号的每日变化趋势。',
    de: 'Tägliche Entwicklung je Konto, gefiltert nach Jahr und Monat.',
    fr: 'Évolution quotidienne par compte, filtrée par année et par mois.',
    es: 'Evolución diaria por cuenta, filtrada por año y mes.',
    ru: 'Ежедневная динамика по каждому аккаунту с фильтром по году и месяцу.',
  },
  saasScreenNotificationTitle: {
    ja: '通知分析',
    en: 'Notification analysis',
    ko: '알림 분석',
    zh: '通知分析',
    de: 'Benachrichtigungsanalyse',
    fr: 'Analyse des notifications',
    es: 'Análisis de notificaciones',
    ru: 'Анализ уведомлений',
  },
  saasScreenNotificationDesc: {
    ja: 'スキ・フォロー・コメントを、曜日別・時間帯別に見ます。',
    en: 'See likes, follows, and comments broken down by day of week and time of day.',
    ko: '좋아요·팔로우·댓글을 요일별·시간대별로 봅니다.',
    zh: '按星期几、按时间段查看点赞、关注、评论。',
    de: 'Likes, Follows und Kommentare nach Wochentag und Tageszeit.',
    fr: 'Likes, follows et commentaires par jour de la semaine et par tranche horaire.',
    es: 'Me gusta, seguimientos y comentarios por día de la semana y franja horaria.',
    ru: 'Лайки, подписки и комментарии по дням недели и времени суток.',
  },
  saasScreenAccessTitle: {
    ja: 'アクセス分析',
    en: 'Access analytics',
    ko: '접속 분석',
    zh: '访问分析',
    de: 'Zugriffsanalyse',
    fr: 'Analyse du trafic',
    es: 'Análisis de accesos',
    ru: 'Анализ посещений',
  },
  saasScreenAccessDesc: {
    ja: 'Google Analytics 4のデータを、地図で見ます（実装予定）。',
    en: 'View Google Analytics 4 data on a map (coming soon).',
    ko: 'Google Analytics 4 데이터를 지도로 봅니다(구현 예정).',
    zh: '在地图上查看 Google Analytics 4 数据（开发中）。',
    de: 'Google-Analytics-4-Daten auf einer Karte (in Vorbereitung).',
    fr: 'Données Google Analytics 4 affichées sur une carte (à venir).',
    es: 'Datos de Google Analytics 4 en un mapa (próximamente).',
    ru: 'Данные Google Analytics 4 на карте (в разработке).',
  },
  saasScreensNote: {
    ja: 'スマホ、タブレット、PCに対応しています。',
    en: 'Works on smartphones, tablets, and PCs.',
    ko: '스마트폰, 태블릿, PC에서 모두 이용할 수 있습니다.',
    zh: '支持手机、平板电脑和电脑访问。',
    de: 'Funktioniert auf Smartphone, Tablet und PC.',
    fr: 'Fonctionne sur smartphone, tablette et ordinateur.',
    es: 'Funciona en smartphones, tabletas y ordenadores.',
    ru: 'Работает на смартфонах, планшетах и компьютерах.',
  },
  saasApproachHeading: {
    ja: 'つくり方の考え方',
    en: 'How I build it',
    ko: '만드는 방식',
    zh: '开发理念',
    de: 'Meine Herangehensweise',
    fr: 'Ma méthode de développement',
    es: 'Mi forma de construirlo',
    ru: 'Подход к разработке',
  },
  saasApproachSelfTitle: {
    ja: 'まず自分から',
    en: 'Start with myself',
    ko: '우선 나부터',
    zh: '先从自己开始',
    de: 'Zuerst ich selbst',
    fr: "D'abord moi-même",
    es: 'Empezar por mí mismo',
    ru: 'Сначала для себя',
  },
  saasApproachSelfDesc: {
    ja: '最初のユーザーは自分です。要件が速く決まり、動かなければすぐに気づけます。',
    en: "I'm the first user. Requirements get settled fast, and I notice right away if something breaks.",
    ko: '첫 사용자는 저 자신입니다. 요구사항이 빠르게 정해지고, 동작하지 않으면 바로 알아챌 수 있습니다.',
    zh: '第一个用户就是我自己。这样需求能很快确定，一旦出问题也能立刻发现。',
    de: 'Der erste Nutzer bin ich selbst. So stehen Anforderungen schnell fest, und Fehler fallen sofort auf.',
    fr: "Je suis mon propre premier utilisateur. Les besoins se précisent vite, et je remarque immédiatement si quelque chose ne fonctionne pas.",
    es: 'El primer usuario soy yo mismo. Los requisitos se definen rápido y noto enseguida si algo falla.',
    ru: 'Я сам — первый пользователь. Требования проясняются быстро, а сбои заметны сразу.',
  },
  saasApproachMultiTenantTitle: {
    ja: '最初から複数の企業に対応',
    en: 'Multi-tenant from day one',
    ko: '처음부터 여러 기업을 지원',
    zh: '从一开始就支持多家企业',
    de: 'Von Anfang an für mehrere Unternehmen',
    fr: 'Multi-entreprises dès le départ',
    es: 'Multiempresa desde el principio',
    ru: 'С самого начала для нескольких компаний',
  },
  saasApproachMultiTenantDesc: {
    ja: '1社で使うところから始めて、複数の企業に提供できる構造で作っています。',
    en: "It starts out serving one company, but it's built with a structure that can serve many.",
    ko: '한 회사에서 사용하는 것부터 시작해, 여러 기업에 제공할 수 있는 구조로 만들고 있습니다.',
    zh: '从一家企业使用开始，但采用可以提供给多家企业的架构进行开发。',
    de: 'Der Einsatz beginnt bei einem Unternehmen, doch die Struktur ist von vornherein für mehrere Unternehmen ausgelegt.',
    fr: "L'usage commence avec une seule entreprise, mais la structure est conçue pour en servir plusieurs.",
    es: 'Empieza usándolo una sola empresa, pero está construido con una estructura pensada para varias empresas.',
    ru: 'Начинается с использования одной компанией, но структура рассчитана на несколько компаний.',
  },
  saasApproachAssetsTitle: {
    ja: '既存の資産を活かす',
    en: 'Reusing existing assets',
    ko: '기존 자산을 활용',
    zh: '善用现有资源',
    de: 'Vorhandenes nutzen',
    fr: "Valoriser l'existant",
    es: 'Aprovechar lo que ya existe',
    ru: 'Использование существующих ресурсов',
  },
  saasApproachAssetsDesc: {
    ja: 'GASとスプレッドシートで集めたデータを、Google Sheets APIで取り込みます。',
    en: 'Data collected with Google Apps Script and Spreadsheets is imported via the Google Sheets API.',
    ko: 'GAS와 스프레드시트로 모은 데이터를 Google Sheets API로 가져옵니다.',
    zh: '通过 Google Sheets API 导入用 GAS 和电子表格收集的数据。',
    de: 'Mit Google Apps Script und Tabellen gesammelte Daten werden über die Google Sheets API eingelesen.',
    fr: "Les données collectées via Google Apps Script et les feuilles de calcul sont importées grâce à l'API Google Sheets.",
    es: 'Los datos recopilados con Google Apps Script y hojas de cálculo se importan mediante la API de Google Sheets.',
    ru: 'Данные, собранные с помощью Google Apps Script и таблиц, импортируются через Google Sheets API.',
  },
  saasApproachMigrationTitle: {
    ja: '移行しやすい構成',
    en: 'Easy to migrate later',
    ko: '이전하기 쉬운 구성',
    zh: '易于迁移的架构',
    de: 'Leicht migrierbare Architektur',
    fr: 'Architecture facile à migrer',
    es: 'Arquitectura fácil de migrar',
    ru: 'Архитектура, удобная для переноса',
  },
  saasApproachMigrationDesc: {
    ja: 'Next.js、Vercel、Supabaseで動いています。将来、AWSやGCP、Azureへ移りやすい構成です。',
    en: 'It runs on Next.js, Vercel, and Supabase — a setup that will move easily to AWS, GCP, or Azure later on.',
    ko: 'Next.js, Vercel, Supabase로 동작합니다. 앞으로 AWS나 GCP, Azure로 옮기기 쉬운 구성입니다.',
    zh: '运行在 Next.js、Vercel、Supabase 之上。未来也易于迁移到 AWS、GCP 或 Azure。',
    de: 'Es läuft auf Next.js, Vercel und Supabase – ein Aufbau, der sich später leicht zu AWS, GCP oder Azure migrieren lässt.',
    fr: 'Il fonctionne sur Next.js, Vercel et Supabase, une architecture qui pourra facilement migrer vers AWS, GCP ou Azure.',
    es: 'Funciona con Next.js, Vercel y Supabase, una configuración que podrá migrarse fácilmente a AWS, GCP o Azure más adelante.',
    ru: 'Работает на Next.js, Vercel и Supabase — эту конфигурацию будет легко перенести на AWS, GCP или Azure в будущем.',
  },
  saasApproachAiTitle: {
    ja: 'AIと開発',
    en: 'Developing with AI',
    ko: 'AI와 함께 개발',
    zh: '与 AI 共同开发',
    de: 'Entwicklung mit KI',
    fr: "Développer avec l'IA",
    es: 'Desarrollo con IA',
    ru: 'Разработка вместе с ИИ',
  },
  saasApproachAiDesc: {
    ja: '仕様書をClaudeと一緒に作り、Claude Codeで実装しています。',
    en: 'I write the specs together with Claude, then implement them with Claude Code.',
    ko: '명세서를 Claude와 함께 작성하고, Claude Code로 구현하고 있습니다.',
    zh: '与 Claude 一起编写规格说明书，并用 Claude Code 进行实现。',
    de: 'Die Spezifikation entsteht gemeinsam mit Claude, die Umsetzung erfolgt mit Claude Code.',
    fr: 'Je rédige les spécifications avec Claude, puis je les implémente avec Claude Code.',
    es: 'Redacto las especificaciones junto con Claude y las implemento con Claude Code.',
    ru: 'Спецификацию я составляю вместе с Claude, а реализую с помощью Claude Code.',
  },
  saasDemoHeading: {
    ja: 'デモサイト',
    en: 'Demo site',
    ko: '데모 사이트',
    zh: '演示网站',
    de: 'Demo-Website',
    fr: 'Site de démonstration',
    es: 'Sitio de demostración',
    ru: 'Демо-сайт',
  },
  saasDemoBody: {
    ja: '実際に動くデモを、お試しいただけます。参照のみのデモ環境で、テストデータで動いています。本番のデータは含まれていません。',
    en: "You're welcome to try the working demo. It's a view-only demo environment running on test data — no production data is included.",
    ko: '실제로 동작하는 데모를 체험하실 수 있습니다. 조회 전용 데모 환경이며 테스트 데이터로 동작합니다. 운영 데이터는 포함되어 있지 않습니다.',
    zh: '欢迎试用实际运行的演示环境。这是一个仅供查看的演示环境，使用测试数据运行，不包含生产数据。',
    de: 'Probieren Sie die funktionierende Demo gern aus. Es handelt sich um eine reine Ansichtsumgebung mit Testdaten – es sind keine Produktionsdaten enthalten.',
    fr: "N'hésitez pas à essayer la démo, pleinement fonctionnelle. Il s'agit d'un environnement de démonstration en lecture seule, avec des données de test — aucune donnée de production n'y figure.",
    es: 'Puede probar la demostración, que funciona de verdad. Es un entorno de solo lectura con datos de prueba; no incluye datos de producción.',
    ru: 'Вы можете опробовать полностью рабочую демоверсию. Это демо-среда только для просмотра, работающая на тестовых данных — производственные данные не используются.',
  },
  saasDemoButton: {
    ja: 'デモサイトを開く',
    en: 'Open the demo site',
    ko: '데모 사이트 열기',
    zh: '打开演示网站',
    de: 'Demo-Website öffnen',
    fr: 'Ouvrir le site de démonstration',
    es: 'Abrir el sitio de demostración',
    ru: 'Открыть демо-сайт',
  },
  saasDemoIdLabel: {
    ja: 'ログインID',
    en: 'Login ID',
    ko: '로그인 ID',
    zh: '登录 ID',
    de: 'Login-ID',
    fr: 'Identifiant',
    es: 'ID de acceso',
    ru: 'Логин',
  },
  saasDemoPasswordLabel: {
    ja: 'パスワード',
    en: 'Password',
    ko: '비밀번호',
    zh: '密码',
    de: 'Passwort',
    fr: 'Mot de passe',
    es: 'Contraseña',
    ru: 'Пароль',
  },
  saasArticleHeading: {
    ja: '関連するnote記事',
    en: 'Related note article',
    ko: '관련 note 게시글',
    zh: '相关 note 文章',
    de: 'Verwandter note-Artikel',
    fr: 'Article note associé',
    es: 'Artículo relacionado en note',
    ru: 'Связанная статья на note',
  },
  saasArticleBody: {
    ja: '開発の経緯と設計の考え方は、noteにまとめています。記事の後半（有料）では、実際にClaude Codeに渡した、仕様書と開発指示書の全文を公開しています。',
    en: "I've written up the background and design thinking on note. In the second, paid half of the article, I publish the full text of the spec and instructions I actually gave to Claude Code.",
    ko: '개발 경위와 설계에 대한 생각은 note에 정리해 두었습니다. 글 후반부(유료)에서는 실제로 Claude Code에 전달한 명세서와 개발 지시서 전문을 공개하고 있습니다.',
    zh: '开发经过与设计思路整理在 note 文章中。文章后半部分（付费）公开了实际提交给 Claude Code 的规格说明书与开发指示书全文。',
    de: 'Hintergrund und Designüberlegungen habe ich auf note zusammengefasst. Im zweiten, kostenpflichtigen Teil des Artikels veröffentliche ich den vollständigen Text der Spezifikation und der Anweisungen, die ich tatsächlich an Claude Code übergeben habe.',
    fr: "J'ai résumé sur note le contexte du développement et ma réflexion sur la conception. Dans la seconde partie de l'article (payante), je publie l'intégralité du cahier des charges et des instructions que j'ai réellement transmis à Claude Code.",
    es: 'He resumido en note los antecedentes y el enfoque del diseño. En la segunda mitad del artículo (de pago) publico el texto completo de las especificaciones e instrucciones que realmente entregué a Claude Code.',
    ru: 'Предысторию разработки и логику проектирования я изложил в статье на note. Во второй, платной части статьи я публикую полный текст спецификации и инструкций, которые реально передал Claude Code.',
  },
  saasArticleLinkLabel: {
    ja: '【マルチテナント型SaaSの開発はまず自分から:デモサイト有り】Vol.4～自分のnoteデータで作るSaaSのリアル、ポートフォリオはデプロイしてから語れ～',
    en: '【マルチテナント型SaaSの開発はまず自分から:デモサイト有り】Vol.4～自分のnoteデータで作るSaaSのリアル、ポートフォリオはデプロイしてから語れ～',
    ko: '【マルチテナント型SaaSの開発はまず自分から:デモサイト有り】Vol.4～自分のnoteデータで作るSaaSのリアル、ポートフォリオはデプロイしてから語れ～',
    zh: '【マルチテナント型SaaSの開発はまず自分から:デモサイト有り】Vol.4～自分のnoteデータで作るSaaSのリアル、ポートフォリオはデプロイしてから語れ～',
    de: '【マルチテナント型SaaSの開発はまず自分から:デモサイト有り】Vol.4～自分のnoteデータで作るSaaSのリアル、ポートフォリオはデプロイしてから語れ～',
    fr: '【マルチテナント型SaaSの開発はまず自分から:デモサイト有り】Vol.4～自分のnoteデータで作るSaaSのリアル、ポートフォリオはデプロイしてから語れ～',
    es: '【マルチテナント型SaaSの開発はまず自分から:デモサイト有り】Vol.4～自分のnoteデータで作るSaaSのリアル、ポートフォリオはデプロイしてから語れ～',
    ru: '【マルチテナント型SaaSの開発はまず自分から:デモサイト有り】Vol.4～自分のnoteデータで作るSaaSのリアル、ポートフォリオはデプロイしてから語れ～',
  },
  saasArticleLangNote: {
    ja: '（記事は日本語です）',
    en: '(The article is in Japanese.)',
    ko: '(글은 일본어로 작성되어 있습니다.)',
    zh: '（文章为日语。）',
    de: '(Der Artikel ist auf Japanisch verfasst.)',
    fr: "(L'article est rédigé en japonais.)",
    es: '(El artículo está escrito en japonés.)',
    ru: '(Статья написана на японском языке.)',
  },
  saasContactHeading: {
    ja: 'ご相談',
    en: 'Get in touch',
    ko: '상담',
    zh: '咨询',
    de: 'Anfrage',
    fr: 'Nous contacter',
    es: 'Consultas',
    ru: 'Консультация',
  },
  saasContactBody: {
    ja: 'SaaSの開発や、データの可視化のご相談は、お問い合わせからどうぞ。',
    en: 'For questions about SaaS development or data visualization, please get in touch.',
    ko: 'SaaS 개발이나 데이터 시각화에 대한 상담은 문의하기를 이용해 주세요.',
    zh: '如需咨询 SaaS 开发或数据可视化相关事宜，请通过咨询页面联系我。',
    de: 'Für Fragen zur SaaS-Entwicklung oder Datenvisualisierung nutzen Sie bitte das Kontaktformular.',
    fr: 'Pour toute question sur le développement SaaS ou la visualisation de données, contactez-moi.',
    es: 'Para consultas sobre desarrollo de SaaS o visualización de datos, póngase en contacto conmigo.',
    ru: 'По вопросам разработки SaaS или визуализации данных, пожалуйста, свяжитесь со мной.',
  },
  saasScreenshotYojitsuAlt: {
    ja: '予実管理ページの複合グラフの画面',
    en: 'Screen showing the target-vs-actual combo chart',
    ko: '목표 대비 실적 페이지의 복합 그래프 화면',
    zh: '目标与实际页面的复合图表画面',
    de: 'Ansicht mit dem Soll-Ist-Kombi-Diagramm',
    fr: 'Écran du graphique combiné objectifs / réalisé',
    es: 'Pantalla del gráfico combinado de objetivo y resultado',
    ru: 'Экран с комбинированной диаграммой плана и факта',
  },
  saasScreenshotDashboardAlt: {
    ja: '複数のグラフが並ぶダッシュボードの画面',
    en: 'Screen showing the dashboard with multiple charts side by side',
    ko: '여러 그래프가 나란히 표시된 대시보드 화면',
    zh: '并排显示多个图表的仪表盘画面',
    de: 'Ansicht des Dashboards mit mehreren nebeneinander angeordneten Diagrammen',
    fr: 'Écran du tableau de bord avec plusieurs graphiques côte à côte',
    es: 'Pantalla del panel con varios gráficos dispuestos juntos',
    ru: 'Экран панели с несколькими диаграммами рядом',
  },
  saasScreenshotFollowerAlt: {
    ja: 'フォロワー数ページの日別推移グラフの画面',
    en: 'Screen showing the daily follower-count trend chart',
    ko: '팔로워 수 페이지의 일별 추이 그래프 화면',
    zh: '粉丝数页面的每日变化趋势图画面',
    de: 'Ansicht mit dem Diagramm der täglichen Follower-Entwicklung',
    fr: "Écran du graphique d'évolution quotidienne des abonnés",
    es: 'Pantalla del gráfico de evolución diaria de seguidores',
    ru: 'Экран с графиком ежедневной динамики подписчиков',
  },
  saasScreenshotNotificationAlt: {
    ja: '通知分析ページの曜日別・時間帯別グラフの画面',
    en: 'Screen showing notifications broken down by day of week and time of day',
    ko: '알림 분석 페이지의 요일별·시간대별 그래프 화면',
    zh: '通知分析页面的按星期与时段划分的图表画面',
    de: 'Ansicht mit Benachrichtigungen nach Wochentag und Tageszeit',
    fr: 'Écran des notifications par jour de la semaine et tranche horaire',
    es: 'Pantalla de notificaciones por día de la semana y franja horaria',
    ru: 'Экран с уведомлениями по дням недели и времени суток',
  },
  saasLearnMoreLabel: {
    ja: '詳しく見る',
    en: 'Learn more',
    ko: '자세히 보기',
    zh: '查看详情',
    de: 'Mehr erfahren',
    fr: 'En savoir plus',
    es: 'Ver más',
    ru: 'Подробнее',
  },

  // ナビ付きLPページ（/navi-lp）
  naviLpHeading: {
    ja: 'ナビ付きLP',
    en: 'Guided LP',
    ko: '가이드형 LP',
    zh: '导览式 LP',
    de: 'Geführte LP',
    fr: 'LP guidée',
    es: 'LP guiada',
    ru: 'LP с гидом',
  },
  naviLpLead: {
    ja: '動画や音声が案内してくれる、「ナビ付き」のLPです。AIと一緒に作った、2つのバリエーションを紹介します。',
    en: "A “guided” LP, led by video or voice. Here are two variations I built with AI.",
    ko: '동영상이나 음성이 안내해 주는 ‘가이드형’ LP입니다. AI와 함께 만든 두 가지 버전을 소개합니다.',
    zh: '这是由视频或语音进行导览的「导览式」LP。介绍我与 AI 一起制作的两种版本。',
    de: 'Eine LP mit Führung: Video oder Stimme leitet Sie durch die Seite. Ich stelle zwei mit KI entwickelte Varianten vor.',
    fr: 'Une LP « guidée », où une vidéo ou une voix vous accompagne. Je présente deux variantes que j’ai créées avec l’IA.',
    es: 'Una LP "guiada", donde un vídeo o una voz le acompaña. Presento dos variantes que he creado con IA.',
    ru: 'LP с гидом — видео или голос ведёт вас по странице. Представляю два варианта, созданных вместе с ИИ.',
  },
  naviLpAboutHeading: {
    ja: 'ナビ付きLPとは',
    en: 'What is a guided LP?',
    ko: '가이드형 LP란',
    zh: '什么是导览式 LP',
    de: 'Was ist eine geführte LP?',
    fr: 'Qu’est-ce qu’une LP guidée ?',
    es: '¿Qué es una LP guiada?',
    ru: 'Что такое LP с гидом',
  },
  naviLpAboutBody: {
    ja: 'ふつうのLPは、読む人が自分で、上から下へ読み進めます。ナビ付きLPは、音声や動画の案内役が話しかけ、ページを一緒に進めてくれます。読む人は、案内に身をまかせるだけで、内容が伝わります。',
    en: "With a normal LP, the reader scrolls from top to bottom on their own. With a guided LP, a voice or video guide talks to the reader and moves through the page together with them. The reader just follows along, and the message gets across.",
    ko: '일반적인 LP는 읽는 사람이 스스로 위에서 아래로 읽어 나갑니다. 가이드형 LP는 음성이나 동영상 안내자가 말을 걸며, 페이지를 함께 진행해 줍니다. 읽는 사람은 안내를 따라가기만 하면 내용이 전달됩니다.',
    zh: '普通的 LP 由阅读者自己从上到下阅读。导览式 LP 则由语音或视频的导览角色主动搭话，与阅读者一起推进页面。阅读者只需跟随导览，就能理解内容。',
    de: 'Bei einer normalen LP scrollt der Leser selbst von oben nach unten. Bei einer geführten LP spricht ein Sprach- oder Video-Guide den Leser an und führt gemeinsam mit ihm durch die Seite. Der Leser muss sich nur führen lassen, und der Inhalt kommt an.',
    fr: 'Sur une LP classique, le lecteur fait défiler la page seul, de haut en bas. Sur une LP guidée, un guide vocal ou vidéo s’adresse au lecteur et avance dans la page avec lui. Le lecteur n’a qu’à se laisser guider pour que le message passe.',
    es: 'En una LP normal, el lector avanza solo de arriba abajo. En una LP guiada, una voz o un vídeo guía habla con el lector y avanza por la página junto con él. El lector solo tiene que dejarse guiar para que el mensaje llegue.',
    ru: 'На обычной LP читатель сам листает страницу сверху вниз. На LP с гидом голосовой или видео-гид обращается к читателю и вместе с ним продвигается по странице. Читателю достаточно довериться гиду — и суть будет понятна.',
  },
  naviLpVariantsHeading: {
    ja: '2つのバリエーション',
    en: 'Two variations',
    ko: '두 가지 버전',
    zh: '两种版本',
    de: 'Zwei Varianten',
    fr: 'Deux variantes',
    es: 'Dos variantes',
    ru: 'Два варианта',
  },
  naviLpGuidedTitle: {
    ja: '音声ガイドLP',
    en: 'Voice-guided LP',
    ko: '음성 가이드 LP',
    zh: '语音导览 LP',
    de: 'Sprachgeführte LP',
    fr: 'LP guidée par la voix',
    es: 'LP guiada por voz',
    ru: 'LP с голосовым гидом',
  },
  naviLpGuidedIntro: {
    ja: '動画の人物が話しかけ、その声に合わせて、ページが動き出します。最後は、面談の相談フォームで止まります。',
    en: 'A person in a video talks to you, and the page moves along with their voice. It ends at a consultation form for a meeting.',
    ko: '영상 속 인물이 말을 걸고, 그 목소리에 맞춰 페이지가 움직입니다. 마지막은 상담 신청 폼에서 멈춥니다.',
    zh: '视频中的人物向你搭话，页面会随着声音而变化。最后停在面谈咨询表单。',
    de: 'Eine Person im Video spricht Sie an, und die Seite bewegt sich im Takt der Stimme. Am Ende landen Sie bei einem Formular zur Terminvereinbarung.',
    fr: 'Une personne en vidéo vous parle, et la page évolue au rythme de sa voix. Elle se termine sur un formulaire de prise de rendez-vous.',
    es: 'Una persona en vídeo le habla, y la página avanza al ritmo de su voz. Termina en un formulario de solicitud de reunión.',
    ru: 'Человек в видео обращается к вам, и страница движется в такт его голосу. В конце — форма для записи на консультацию.',
  },
  naviLpGuidedPoint1: {
    ja: '動画、音声、ページの動きが、ひとつにつながります。',
    en: 'Video, voice, and page motion are all connected as one.',
    ko: '동영상, 음성, 페이지의 움직임이 하나로 이어집니다.',
    zh: '视频、语音与页面动效融为一体。',
    de: 'Video, Stimme und Seitenbewegung sind miteinander verbunden.',
    fr: 'Vidéo, voix et animation de la page ne font qu’un.',
    es: 'El vídeo, la voz y el movimiento de la página se conectan en uno.',
    ru: 'Видео, голос и движение страницы объединены в единое целое.',
  },
  naviLpGuidedPoint2: {
    ja: '話が進むと、その内容のセクションが現れます。',
    en: 'As the talk moves forward, the matching section appears.',
    ko: '이야기가 진행되면, 그 내용에 맞는 섹션이 나타납니다.',
    zh: '话题推进时，对应的内容区块会随之出现。',
    de: 'Sobald das Gespräch weitergeht, erscheint der passende Abschnitt.',
    fr: 'À mesure que le discours avance, la section correspondante apparaît.',
    es: 'A medida que avanza el discurso, aparece la sección correspondiente.',
    ru: 'По мере развития рассказа появляется соответствующий раздел.',
  },
  naviLpGuidedPoint3: {
    ja: '最後は、相談フォームへ。候補日時を選んで送れます。すぐに予約が確定するのではなく、メールの返信で日程を決めます。',
    en: "It ends at a consultation form. You can pick candidate times and send them. The meeting isn't confirmed instantly — the schedule is set by an email reply.",
    ko: '마지막은 상담 신청 폼입니다. 희망 일시를 선택해 보낼 수 있습니다. 바로 예약이 확정되는 것이 아니라, 이메일 답장으로 일정을 정합니다.',
    zh: '最后是咨询表单。可以选择候选时间并发送。并非立即确定预约，而是通过邮件回复来确定日程。',
    de: 'Am Ende steht ein Anfrageformular. Sie können mehrere Terminvorschläge auswählen und absenden. Der Termin wird nicht sofort bestätigt, sondern per E-Mail-Antwort vereinbart.',
    fr: 'Elle se termine par un formulaire de demande. Vous pouvez choisir des créneaux proposés et les envoyer. Le rendez-vous n’est pas confirmé immédiatement : la date est fixée par une réponse par e-mail.',
    es: 'Termina en un formulario de solicitud. Puede elegir horarios propuestos y enviarlos. La cita no se confirma al instante: la fecha se decide con una respuesta por correo.',
    ru: 'В конце — форма заявки. Можно выбрать предполагаемое время и отправить. Встреча подтверждается не мгновенно — дата согласовывается ответным письмом.',
  },
  naviLpGuidedPoint4: {
    ja: '今は日本語版です。今後、8か国語に広げる予定です。',
    en: "It's currently Japanese-only. I plan to expand it to 8 languages later.",
    ko: '지금은 일본어판입니다. 앞으로 8개 언어로 넓힐 예정입니다.',
    zh: '目前仅有日语版本。今后计划扩展至 8 种语言。',
    de: 'Aktuell nur auf Japanisch verfügbar. Eine Erweiterung auf 8 Sprachen ist geplant.',
    fr: 'Actuellement disponible uniquement en japonais. Une extension à 8 langues est prévue.',
    es: 'Por ahora solo está en japonés. Está previsto ampliarla a 8 idiomas.',
    ru: 'Пока доступна только на японском. В будущем планирую расширить до 8 языков.',
  },
  naviLpGuidedSuitable: {
    ja: '向いている場面：ひとつのストーリーを、順番に伝えて、相談につなげたいとき。',
    en: 'Good for: telling one story in order and leading into a consultation.',
    ko: '이런 상황에 적합: 하나의 스토리를 순서대로 전달하고 상담으로 연결하고 싶을 때.',
    zh: '适用场景：想按顺序讲述一个完整故事，并引导至咨询时。',
    de: 'Geeignet für: eine Geschichte der Reihe nach erzählen und zu einer Anfrage führen.',
    fr: 'Idéal pour : raconter une histoire dans l’ordre et déboucher sur une prise de contact.',
    es: 'Ideal para: contar una historia en orden y llevar a una consulta.',
    ru: 'Подходит для: последовательного рассказа одной истории с переходом к консультации.',
  },
  naviLpGuidedButton: {
    ja: '音声ガイドLPを開く',
    en: 'Open the voice-guided LP',
    ko: '음성 가이드 LP 열기',
    zh: '打开语音导览 LP',
    de: 'Sprachgeführte LP öffnen',
    fr: 'Ouvrir la LP guidée par la voix',
    es: 'Abrir la LP guiada por voz',
    ru: 'Открыть LP с голосовым гидом',
  },
  naviLpGuidedScreenshotAlt: {
    ja: '音声ガイドLPで、動画の案内役がページを進めている画面',
    en: 'Screen showing the voice-guided LP with a video guide leading the page',
    ko: '음성 가이드 LP에서 영상 안내자가 페이지를 진행하는 화면',
    zh: '语音导览 LP 中视频导览角色引导页面的画面',
    de: 'Ansicht der sprachgeführten LP mit Video-Guide, der durch die Seite führt',
    fr: 'Écran de la LP guidée par la voix, avec un guide vidéo qui fait avancer la page',
    es: 'Pantalla de la LP guiada por voz, con un guía en vídeo que avanza por la página',
    ru: 'Экран LP с голосовым гидом, где видео-гид продвигает страницу',
  },
  naviLpGuidedArticleLinkLabel: {
    ja: '【AIとLPづくり】GPT-5.6 Solで仕様を固め、GPT-6 Astraで実装したら「動画が話し、ページが動くLP」ができた',
    en: '【AIとLPづくり】GPT-5.6 Solで仕様を固め、GPT-6 Astraで実装したら「動画が話し、ページが動くLP」ができた',
    ko: '【AIとLPづくり】GPT-5.6 Solで仕様を固め、GPT-6 Astraで実装したら「動画が話し、ページが動くLP」ができた',
    zh: '【AIとLPづくり】GPT-5.6 Solで仕様を固め、GPT-6 Astraで実装したら「動画が話し、ページが動くLP」ができた',
    de: '【AIとLPづくり】GPT-5.6 Solで仕様を固め、GPT-6 Astraで実装したら「動画が話し、ページが動くLP」ができた',
    fr: '【AIとLPづくり】GPT-5.6 Solで仕様を固め、GPT-6 Astraで実装したら「動画が話し、ページが動くLP」ができた',
    es: '【AIとLPづくり】GPT-5.6 Solで仕様を固め、GPT-6 Astraで実装したら「動画が話し、ページが動くLP」ができた',
    ru: '【AIとLPづくり】GPT-5.6 Solで仕様を固め、GPT-6 Astraで実装したら「動画が話し、ページが動くLP」ができた',
  },
  naviLpLpNotesTitle: {
    ja: 'LPNotes',
    en: 'LPNotes',
    ko: 'LPNotes',
    zh: 'LPNotes',
    de: 'LPNotes',
    fr: 'LPNotes',
    es: 'LPNotes',
    ru: 'LPNotes',
  },
  naviLpLpNotesTagline: {
    ja: '記事のように書き足して育てるLP',
    en: 'An LP you grow by writing more, like an article',
    ko: '글처럼 계속 써 나가며 키우는 LP',
    zh: '像写文章一样不断续写、逐步成长的 LP',
    de: 'Eine LP, die wie ein Artikel wächst',
    fr: 'Une LP que l’on fait grandir en l’écrivant, comme un article',
    es: 'Una LP que crece a medida que se escribe, como un artículo',
    ru: 'LP, которая растёт, как статья, по мере дописывания',
  },
  naviLpLpNotesIntro: {
    ja: 'note記事のように書くと、1つのアイデアが1つのページになる、自分専用のLPの実験サイトです。',
    en: "Write it like a note article, and one idea becomes one page — it's my personal experimental site for LPs.",
    ko: 'note 글처럼 쓰면 하나의 아이디어가 하나의 페이지가 되는, 저만의 LP 실험 사이트입니다.',
    zh: '像写 note 文章一样撰写，一个想法就会变成一个页面——这是我个人的 LP 实验网站。',
    de: 'Schreiben Sie wie einen note-Artikel, und aus einer Idee wird eine Seite – meine persönliche Experimentierseite für LPs.',
    fr: 'En écrivant comme un article note, une idée devient une page : c’est mon site expérimental personnel pour les LP.',
    es: 'Al escribir como un artículo de note, una idea se convierte en una página: es mi sitio experimental personal para LP.',
    ru: 'Пишешь как статью note — и одна идея превращается в одну страницу. Это мой личный экспериментальный сайт для LP.',
  },
  naviLpLpNotesPoint1: {
    ja: '記事のように書き足せます。画像、見出し、相談フォームを入れられます。',
    en: 'You can keep adding to it like an article — images, headings, and a consultation form all fit in.',
    ko: '글처럼 계속 이어서 쓸 수 있습니다. 이미지, 제목, 상담 폼을 넣을 수 있습니다.',
    zh: '可以像写文章一样不断续写，能插入图片、标题和咨询表单。',
    de: 'Sie können wie bei einem Artikel weiterschreiben – Bilder, Überschriften und ein Anfrageformular lassen sich einfügen.',
    fr: 'Vous pouvez continuer à l’écrire comme un article : images, titres et formulaire de contact peuvent y être ajoutés.',
    es: 'Puede seguir escribiendo como un artículo: se pueden añadir imágenes, títulos y un formulario de consulta.',
    ru: 'Можно дописывать как статью — добавлять изображения, заголовки и форму для консультации.',
  },
  naviLpLpNotesPoint2: {
    ja: '8か国語に対応しています。地球儀で言語を切り替えられます。',
    en: 'Supports 8 languages. You can switch languages with the globe.',
    ko: '8개 언어를 지원합니다. 지구본으로 언어를 전환할 수 있습니다.',
    zh: '支持 8 种语言，可通过地球仪切换语言。',
    de: 'Unterstützt 8 Sprachen. Über den Globus lässt sich die Sprache umschalten.',
    fr: 'Disponible en 8 langues. Le globe permet de changer de langue.',
    es: 'Disponible en 8 idiomas. Puede cambiar de idioma con el globo terráqueo.',
    ru: 'Поддерживает 8 языков. Переключить язык можно с помощью глобуса.',
  },
  naviLpLpNotesPoint3: {
    ja: 'エリカと一緒に、音声で読み進められます。口の動きも付いています。',
    en: 'Erica reads it aloud with you, complete with moving lips.',
    ko: '에리카와 함께 음성으로 읽어 나갈 수 있습니다. 입 모양도 함께 움직입니다.',
    zh: '可以和 Erica 一起用语音朗读，还带有口型动作。',
    de: 'Erica liest gemeinsam mit Ihnen vor – inklusive Mundbewegung.',
    fr: 'Erica vous accompagne à voix haute, avec un mouvement des lèvres synchronisé.',
    es: 'Erica la lee en voz alta junto con usted, con movimiento de labios incluido.',
    ru: 'Эрика читает вместе с вами вслух, с синхронным движением губ.',
  },
  naviLpLpNotesPoint4: {
    ja: '詳しい制作の記録は、noteの記事（一部有料）にまとめています。',
    en: 'The detailed build log is written up in a note article (partly paid).',
    ko: '자세한 제작 기록은 note 글(일부 유료)에 정리해 두었습니다.',
    zh: '详细的制作记录整理在 note 文章中（部分付费）。',
    de: 'Ein ausführliches Entwicklungsprotokoll habe ich in einem note-Artikel (teilweise kostenpflichtig) festgehalten.',
    fr: 'Le journal de développement détaillé est disponible dans un article note (en partie payant).',
    es: 'El registro detallado de la creación está recogido en un artículo de note (parcialmente de pago).',
    ru: 'Подробный дневник разработки описан в статье на note (частично платная).',
  },
  naviLpLpNotesSuitable: {
    ja: '向いている場面：たくさんのLPを次々に書いて、反応を試したいとき。',
    en: 'Good for: writing many LPs one after another and testing the response.',
    ko: '이런 상황에 적합: 많은 LP를 잇달아 작성해 반응을 시험해 보고 싶을 때.',
    zh: '适用场景：想连续撰写多个 LP，测试反响时。',
    de: 'Geeignet für: viele LPs nacheinander schreiben und die Reaktion testen.',
    fr: 'Idéal pour : écrire de nombreuses LP les unes après les autres et tester les réactions.',
    es: 'Ideal para: escribir muchas LP una tras otra y probar la respuesta.',
    ru: 'Подходит для: быстрого написания множества LP подряд и проверки реакции.',
  },
  naviLpLpNotesScreenshotAlt: {
    ja: 'LPNotesで、記事のように書かれたページが表示された画面',
    en: 'Screen showing an LPNotes page written like an article',
    ko: 'LPNotes에서 글처럼 작성된 페이지가 표시된 화면',
    zh: 'LPNotes 中以文章形式撰写的页面画面',
    de: 'Ansicht einer LPNotes-Seite, geschrieben wie ein Artikel',
    fr: 'Écran d’une page LPNotes rédigée comme un article',
    es: 'Pantalla de una página de LPNotes escrita como un artículo',
    ru: 'Экран страницы LPNotes, написанной как статья',
  },
  naviLpLpNotesArticleLinkLabel: {
    ja: 'GPT-6 Astraで自分専用LPサイトを作った――8言語の翻訳・読み上げから一般公開まで',
    en: 'GPT-6 Astraで自分専用LPサイトを作った――8言語の翻訳・読み上げから一般公開まで',
    ko: 'GPT-6 Astraで自分専用LPサイトを作った――8言語の翻訳・読み上げから一般公開まで',
    zh: 'GPT-6 Astraで自分専用LPサイトを作った――8言語の翻訳・読み上げから一般公開まで',
    de: 'GPT-6 Astraで自分専用LPサイトを作った――8言語の翻訳・読み上げから一般公開まで',
    fr: 'GPT-6 Astraで自分専用LPサイトを作った――8言語の翻訳・読み上げから一般公開まで',
    es: 'GPT-6 Astraで自分専用LPサイトを作った――8言語の翻訳・読み上げから一般公開まで',
    ru: 'GPT-6 Astraで自分専用LPサイトを作った――8言語の翻訳・読み上げから一般公開まで',
  },
  naviLpChoiceHeading: {
    ja: '選び方の目安',
    en: 'Which one to choose',
    ko: '선택 기준',
    zh: '选择参考',
    de: 'Entscheidungshilfe',
    fr: 'Comment choisir',
    es: 'Cómo elegir',
    ru: 'Как выбрать',
  },
  naviLpChoiceLine1: {
    ja: '決まった流れで伝えたい：音声ガイドLP',
    en: 'Want to tell it in a fixed flow: the voice-guided LP',
    ko: '정해진 흐름으로 전달하고 싶다면: 음성 가이드 LP',
    zh: '想按固定顺序传达：语音导览 LP',
    de: 'Wenn Sie einen festen Ablauf erzählen möchten: die sprachgeführte LP',
    fr: 'Pour raconter selon un déroulé fixe : la LP guidée par la voix',
    es: 'Para contar con un flujo fijo: la LP guiada por voz',
    ru: 'Хотите рассказывать в заданной последовательности: LP с голосовым гидом',
  },
  naviLpChoiceLine2: {
    ja: 'アイデアを次々と試したい：LPNotes',
    en: 'Want to try ideas one after another: LPNotes',
    ko: '아이디어를 잇달아 시험해 보고 싶다면: LPNotes',
    zh: '想不断尝试新想法：LPNotes',
    de: 'Wenn Sie Ideen nacheinander ausprobieren möchten: LPNotes',
    fr: 'Pour tester des idées les unes après les autres : LPNotes',
    es: 'Para probar ideas una tras otra: LPNotes',
    ru: 'Хотите пробовать идеи одну за другой: LPNotes',
  },
  naviLpContactHeading: {
    ja: 'ご相談',
    en: 'Get in touch',
    ko: '상담',
    zh: '咨询',
    de: 'Anfrage',
    fr: 'Nous contacter',
    es: 'Consultas',
    ru: 'Консультация',
  },
  naviLpContactBody: {
    ja: 'LPの制作や、ナビ付きの仕組みのご相談は、お問い合わせからどうぞ。',
    en: 'For questions about building an LP or a guided setup, please get in touch.',
    ko: 'LP 제작이나 가이드 방식에 대한 상담은 문의하기를 이용해 주세요.',
    zh: '如需咨询 LP 制作或导览机制相关事宜，请通过咨询页面联系我。',
    de: 'Für Fragen zur LP-Erstellung oder zum geführten Aufbau nutzen Sie bitte das Kontaktformular.',
    fr: 'Pour toute question sur la création d’une LP ou le système guidé, contactez-moi.',
    es: 'Para consultas sobre la creación de una LP o el sistema guiado, póngase en contacto conmigo.',
    ru: 'По вопросам создания LP или системы с гидом, пожалуйста, свяжитесь со мной.',
  },

  // /business「制作の紹介」セクション（/saas・/navi-lp へのカードリンク）
  businessShowcaseHeading: {
    ja: '制作の紹介',
    en: 'Featured projects',
    ko: '제작 소개',
    zh: '作品介绍',
    de: 'Vorgestellte Projekte',
    fr: 'Projets réalisés',
    es: 'Proyectos destacados',
    ru: 'Избранные проекты',
  },

  // /privacy: GA4利用のお知らせ（本文・リンク文言）
  privacyGa4Notice: {
    ja: '当サイトは、Google アナリティクス4を使って、アクセス状況を分析しています。詳しくは、次のポリシーをご覧ください。',
    en: 'This site uses Google Analytics 4 to analyze traffic. For details, please see the following policy.',
    ko: '이 사이트는 Google 애널리틱스4를 사용하여 방문 현황을 분석하고 있습니다. 자세한 내용은 다음 정책을 확인해 주세요.',
    zh: '本网站使用 Google Analytics 4（GA4）分析访问情况。详情请查看以下政策。',
    de: 'Diese Website verwendet Google Analytics 4, um die Zugriffe zu analysieren. Weitere Informationen finden Sie in der folgenden Richtlinie.',
    fr: 'Ce site utilise Google Analytics 4 pour analyser la fréquentation. Pour en savoir plus, veuillez consulter la politique suivante.',
    es: 'Este sitio utiliza Google Analytics 4 para analizar el tráfico. Para más información, consulte la siguiente política.',
    ru: 'Этот сайт использует Google Analytics 4 для анализа посещаемости. Подробнее см. в следующей политике.',
  },
  privacyGa4LinkLabel: {
    ja: 'Googleのポリシー',
    en: "Google's policy",
    ko: 'Google 정책',
    zh: 'Google 政策',
    de: 'Google-Richtlinie',
    fr: 'Politique de Google',
    es: 'Política de Google',
    ru: 'Политика Google',
  },

  // イメージ100計算ページ（/image100）
  image100Heading: {
    ja: 'イメージ100計算',
    en: 'Image 100 Calculation',
    ko: '이미지 100 계산',
    zh: '图像100计算',
    de: 'Bild-100-Rechnen',
    fr: 'Calcul Image 100',
    es: 'Cálculo Imagen 100',
    ru: 'Расчёт «Картинка 100»',
  },
  image100Lead: {
    ja: '言語脳を刺激したら、計算脳も刺激して、頭の柔軟体操で、一息入れて、リラックスしましょう',
    en: 'After stimulating your language brain, let’s stimulate your math brain too — take a mental stretch break and relax.',
    ko: '언어 뇌를 자극했다면, 계산 뇌도 자극해서 머리를 유연하게 풀어주며 잠시 쉬어가세요.',
    zh: '刺激了语言脑之后，也来刺激一下计算脑，做个头脑柔软操，稍作休息，放松一下吧。',
    de: 'Nachdem Sie Ihr Sprachgehirn angeregt haben, aktivieren Sie auch Ihr Rechengehirn – gönnen Sie sich eine geistige Dehnübung und entspannen Sie sich.',
    fr: 'Après avoir stimulé votre cerveau du langage, stimulez aussi votre cerveau du calcul : faites une pause détente avec un peu de gymnastique mentale.',
    es: 'Después de estimular tu cerebro del lenguaje, estimula también tu cerebro del cálculo: haz una pausa de estiramiento mental y relájate.',
    ru: 'Простимулировав языковой мозг, простимулируйте и счётный — сделайте лёгкую умственную разминку и немного расслабьтесь.',
  },
  image100HowToIntro: {
    ja: '縦横の見出しが交わるマスを見て、その2つの数字を、頭の中で、足したり、引いたり、掛けたりして、声に出す遊びです。',
    en: 'Look at the cell where a row heading and a column heading meet, add, subtract, or multiply the two numbers in your head, and say the answer out loud.',
    ko: '가로와 세로 머리글이 만나는 칸을 보고, 그 두 숫자를 머릿속으로 더하거나 빼거나 곱해서 소리 내어 말하는 놀이입니다.',
    zh: '看着横向和纵向标题相交的格子，在脑海中把那两个数字加、减或乘，然后大声说出来。',
    de: 'Schauen Sie auf die Zelle, in der sich die waagerechte und die senkrechte Überschrift kreuzen, addieren, subtrahieren oder multiplizieren Sie die beiden Zahlen im Kopf und sagen Sie das Ergebnis laut.',
    fr: "Regardez la case où se croisent l'en-tête horizontal et l'en-tête vertical, additionnez, soustrayez ou multipliez les deux nombres dans votre tête, puis dites le résultat à voix haute.",
    es: 'Mira la casilla donde se cruzan el encabezado horizontal y el vertical, suma, resta o multiplica esos dos números mentalmente y di el resultado en voz alta.',
    ru: 'Посмотрите на ячейку, где пересекаются горизонтальный и вертикальный заголовки, сложите, вычтите или умножьте эти два числа в уме и произнесите ответ вслух.',
  },
  image100HowToExampleAnswerOnly: {
    ja: '例：答えだけを言う → 「5」（five）',
    en: 'Example: say just the answer → "5" (five)',
    ko: '예: 답만 말하기 → "5"（five）',
    zh: '例如：只说答案 → "5"（five）',
    de: 'Beispiel: nur die Antwort sagen → „5“ (five)',
    fr: 'Exemple : dire seulement la réponse → « 5 » (five)',
    es: 'Ejemplo: decir solo la respuesta → "5" (five)',
    ru: 'Пример: сказать только ответ → «5» (five)',
  },
  image100HowToExampleFullSentence: {
    ja: '例：英語で計算式ごと言う → 「one plus four equal five」',
    en: 'Example: say the whole equation in English → "one plus four equal five"',
    ko: '예: 영어로 식까지 통째로 말하기 → "one plus four equal five"',
    zh: '例如：用英语把算式整个说出来 → "one plus four equal five"',
    de: 'Beispiel: die ganze Rechnung auf Englisch sagen → „one plus four equal five“',
    fr: "Exemple : dire toute l'opération en anglais → « one plus four equal five »",
    es: 'Ejemplo: decir toda la operación en inglés → "one plus four equal five"',
    ru: 'Пример: произнести весь пример по-английски → «one plus four equal five»',
  },
  image100HowToExampleSubtraction: {
    ja: '例：引き算の言い方（答えがマイナスになる例） → 「three minus four is minus one」',
    en: 'Example: how to say subtraction (with a negative answer) → "three minus four is minus one"',
    ko: '예: 뺄셈을 말하는 법（답이 마이너스가 되는 예） → "three minus four is minus one"',
    zh: '例如：减法的说法（答案是负数的例子） → "three minus four is minus one"',
    de: 'Beispiel: Subtraktion sagen (mit negativem Ergebnis) → „three minus four is minus one“',
    fr: 'Exemple : comment dire une soustraction (avec un résultat négatif) → « three minus four is minus one »',
    es: 'Ejemplo: cómo decir una resta (con resultado negativo) → "three minus four is minus one"',
    ru: 'Пример: как сказать вычитание (с отрицательным ответом) → «three minus four is minus one»',
  },
  image100HowToExampleMultiplicationTimes: {
    ja: '例：「times」を使う、かけ算の言い方（学校で習う、標準の言い方） → 「two times four is eight」',
    en: 'Example: multiplication using "times" (the standard way taught at school) → "two times four is eight"',
    ko: '예: "times"를 사용하는 곱셈 표현（학교에서 배우는 표준적인 말투） → "two times four is eight"',
    zh: '例如：用"times"表达乘法（学校教的标准说法） → "two times four is eight"',
    de: 'Beispiel: Multiplikation mit „times“ (die im Unterricht übliche Standardform) → „two times four is eight“',
    fr: "Exemple : multiplication avec « times » (la forme standard enseignée à l'école) → « two times four is eight »",
    es: 'Ejemplo: multiplicación usando "times" (la forma estándar que se enseña en la escuela) → "two times four is eight"',
    ru: 'Пример: умножение со словом «times» (стандартная форма, которую учат в школе) → «two times four is eight»',
  },
  image100HowToExampleMultiplication: {
    ja: '例：「by」を使う、かけ算の言い方 → 「two by four is eight」',
    en: 'Example: multiplication using "by" → "two by four is eight"',
    ko: '예: "by"를 사용하는 곱셈 표현 → "two by four is eight"',
    zh: '例如：用"by"表达乘法 → "two by four is eight"',
    de: 'Beispiel: Multiplikation mit „by“ → „two by four is eight“',
    fr: 'Exemple : multiplication avec « by » → « two by four is eight »',
    es: 'Ejemplo: multiplicación usando "by" → "two by four is eight"',
    ru: 'Пример: умножение со словом «by» → «two by four is eight»',
  },
  image100HowToExampleNote: {
    ja: '※ 言い方は、いろいろあります。好きな言い方で、声に出してみましょう。',
    en: 'Note: there are many ways to say it — try whichever feels natural to you.',
    ko: '※ 말하는 방법은 다양합니다. 편한 방식으로 소리 내어 말해 보세요.',
    zh: '※ 说法有很多种，用自己喜欢的方式大声说出来吧。',
    de: 'Hinweis: Es gibt viele Arten, es zu sagen – probieren Sie aus, was Ihnen am natürlichsten vorkommt.',
    fr: 'Remarque : il existe plusieurs façons de le dire, essayez celle qui vous semble la plus naturelle.',
    es: 'Nota: hay muchas formas de decirlo; prueba la que te resulte más natural.',
    ru: 'Примечание: сказать это можно по-разному — попробуйте вариант, который вам удобнее.',
  },
  image100ModeLabel: {
    ja: '並び',
    en: 'Order',
    ko: '순서',
    zh: '排列',
    de: 'Reihenfolge',
    fr: 'Ordre',
    es: 'Orden',
    ru: 'Порядок',
  },
  image100ModeRandom: {
    ja: 'ランダム',
    en: 'Random',
    ko: '랜덤',
    zh: '随机',
    de: 'Zufällig',
    fr: 'Aléatoire',
    es: 'Aleatorio',
    ru: 'Случайно',
  },
  image100ModeKuku: {
    ja: '九九',
    en: 'In order',
    ko: '순서대로',
    zh: '顺序',
    de: 'Der Reihe nach',
    fr: "Dans l'ordre",
    es: 'En orden',
    ru: 'По порядку',
  },
  image100OperatorLabel: {
    ja: '演算',
    en: 'Operation',
    ko: '연산',
    zh: '运算',
    de: 'Rechenart',
    fr: 'Opération',
    es: 'Operación',
    ru: 'Действие',
  },
  // セルの aria-label（例: 「2かける8を再生」）。{h}/{op}/{v} を置換して使う。
  image100CellPlayAriaLabel: {
    ja: '{h}{op}{v}を再生',
    en: 'Play {h} {op} {v}',
    ko: '{h} {op} {v} 재생',
    zh: '播放{h}{op}{v}',
    de: '{h} {op} {v} abspielen',
    fr: 'Lire {h} {op} {v}',
    es: 'Reproducir {h} {op} {v}',
    ru: 'Воспроизвести {h} {op} {v}',
  },
  // 割り算で縦が0（0で割る）のセルの aria-label。「答えが存在しない」ことを
  // 案内する再生ボタンであることを伝える。{h}/{op}/{v} を置換して使う。
  image100CellPlayNoAnswerAriaLabel: {
    ja: '{h}{op}{v}（答えなし）を再生',
    en: 'Play {h} {op} {v} (no answer)',
    ko: '{h} {op} {v}（답 없음）재생',
    zh: '播放{h}{op}{v}（无解）',
    de: '{h} {op} {v} (keine Lösung) abspielen',
    fr: 'Lire {h} {op} {v} (pas de solution)',
    es: 'Reproducir {h} {op} {v} (sin solución)',
    ru: 'Воспроизвести {h} {op} {v} (нет решения)',
  },
  // スクリーンリーダー向けの表キャプション（視覚的には隠す）
  image100TableCaption: {
    ja: '計算練習用の表。上端の行が横の見出しの数字、左端の列が縦の見出しの数字です。中の100マスは、すべて空欄です。',
    en: 'Calculation practice table. The top row shows the horizontal heading numbers, and the left column shows the vertical heading numbers. All 100 inner cells are empty.',
    ko: '계산 연습용 표입니다. 맨 위 행은 가로 머리글 숫자, 맨 왼쪽 열은 세로 머리글 숫자입니다. 안쪽 100칸은 모두 비어 있습니다.',
    zh: '计算练习表格。最上面一行是横向标题数字，最左边一列是纵向标题数字。里面的100个格子全部为空。',
    de: 'Rechenübungstabelle. Die oberste Zeile zeigt die waagerechten Überschriftszahlen, die linke Spalte die senkrechten Überschriftszahlen. Alle 100 inneren Zellen sind leer.',
    fr: "Tableau d'exercice de calcul. La ligne du haut indique les nombres d'en-tête horizontaux, la colonne de gauche les nombres d'en-tête verticaux. Les 100 cases intérieures sont toutes vides.",
    es: 'Tabla de práctica de cálculo. La fila superior muestra los números de encabezado horizontales y la columna izquierda los números de encabezado verticales. Las 100 casillas interiores están todas vacías.',
    ru: 'Таблица для тренировки счёта. В верхней строке — числа горизонтального заголовка, в левом столбце — числа вертикального заголовка. Все 100 внутренних ячеек пусты.',
  },
  image100ContactHeading: {
    ja: 'ご相談',
    en: 'Get in touch',
    ko: '상담',
    zh: '咨询',
    de: 'Anfrage',
    fr: 'Nous contacter',
    es: 'Consultas',
    ru: 'Консультация',
  },
  image100ContactBody: {
    ja: 'イメージ100計算や、ほかのページについてのご相談は、お問い合わせからどうぞ。',
    en: 'For questions about Image 100 Calculation or other pages, please get in touch.',
    ko: '이미지 100 계산이나 다른 페이지에 대한 상담은 문의하기를 이용해 주세요.',
    zh: '如需咨询图像100计算或其他页面相关事宜，请通过咨询页面联系我。',
    de: 'Für Fragen zu Bild-100-Rechnen oder anderen Seiten nutzen Sie bitte das Kontaktformular.',
    fr: 'Pour toute question sur le Calcul Image 100 ou d’autres pages, contactez-moi.',
    es: 'Para consultas sobre el Cálculo Imagen 100 u otras páginas, póngase en contacto conmigo.',
    ru: 'По вопросам о «Расчёт «Картинка 100»» или других страницах, пожалуйста, свяжитесь со мной.',
  },
} satisfies Record<string, Localized>;

export type UiStringKey = keyof typeof UI_STRINGS;

// 指定キーの文言を lang に応じて返す。lang は Cookie / searchParams で解決済みの値を渡す。
// 対象言語のキーが無ければ日本語にフォールバックする。
// {n} / {max} などのプレースホルダを含むキーは呼び出し側で置換する。
export const ui = (key: UiStringKey, lang: Lang | string | undefined): string => {
  const entry: Localized = UI_STRINGS[key];
  const resolved = resolveLang(lang);
  return (resolved !== 'ja' && entry[resolved]) || entry.ja;
};
